-- ================================================================
-- SERVICE_TYPE
-- ================================================================
INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Fixação de Placas/Quadros', 'Manutenção Corretiva Artífice'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'ARTÍFICE'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Fixação de Placas/Quadros'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Outros', 'Manutenção Corretiva Artífice'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'ARTÍFICE'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Outros'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Regulagem de porta', 'Manutenção Corretiva Artífice'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'ARTÍFICE'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Regulagem de porta'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Reparos em móveis', 'Manutenção Corretiva Artífice'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'ARTÍFICE'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Reparos em móveis'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Substituição de dispenser (papel higiênico, papel toalha ou sabão)', 'Manutenção Corretiva Artífice'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'ARTÍFICE'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Substituição de dispenser (papel higiênico, papel toalha ou sabão)'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Substituição de fitas de demarcação lisa/antiderrapante', 'Manutenção Corretiva Artífice'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'ARTÍFICE'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Substituição de fitas de demarcação lisa/antiderrapante'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Substituição de tampa de vaso sanitário', 'Manutenção Corretiva Artífice'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'ARTÍFICE'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Substituição de tampa de vaso sanitário'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Troca de fechadura/miolo', 'Manutenção Corretiva Artífice'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'ARTÍFICE'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Troca de fechadura/miolo'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Equipamento com avaria evidente', 'Manutenção Corretiva Climatização e Refrigeração'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Equipamento com avaria evidente'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Equipamento não liga', 'Manutenção Corretiva Climatização e Refrigeração'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Equipamento não liga'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Equipamento não refrigera/climatiza', 'Manutenção Corretiva Climatização e Refrigeração'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Equipamento não refrigera/climatiza'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Instalação de equipamento', 'Manutenção Corretiva Climatização e Refrigeração'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Instalação de equipamento'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Outros', 'Manutenção Corretiva Climatização e Refrigeração'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Outros'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Remanejamento de unidade evaporadora/condensadora', 'Manutenção Corretiva Climatização e Refrigeração'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Remanejamento de unidade evaporadora/condensadora'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Vazamento de água em equipamento', 'Manutenção Corretiva Climatização e Refrigeração'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Vazamento de água em equipamento'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Limpeza de geladeira ou micro-ondas', 'SERVIÇOS'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'COPA'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Limpeza de geladeira ou micro-ondas'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Dificuldade com a reserva', 'Aplicativo'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'Dúvida Aplicativo'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Dificuldade com a reserva'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Interruptor ou Tomada com defeito/quebrado', 'Manutenção Corretiva Elétrica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Interruptor ou Tomada com defeito/quebrado'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Lâmpadas queimadas', 'Manutenção Corretiva Elétrica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Lâmpadas queimadas'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Montagem de infraestrutura elétrica', 'Nova Obra'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Montagem de infraestrutura elétrica'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Outros', 'Manutenção Corretiva Elétrica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Outros'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Quadro elétrico desarmando', 'Manutenção Corretiva Elétrica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Quadro elétrico desarmando'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Regularização de extensões/plugs/equipamentos', 'Manutenção Corretiva Elétrica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Regularização de extensões/plugs/equipamentos'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Remoção ou Instalação de ponto de tomada', 'Manutenção Corretiva Elétrica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Remoção ou Instalação de ponto de tomada'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Substituição de biruta', 'Manutenção Corretiva Elétrica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Substituição de biruta'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Tomada com defeito/quebrada', 'Manutenção Corretiva Elétrica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Tomada com defeito/quebrada'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Ambiente sem água', 'Manutenção Corretiva Hidráulica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Ambiente sem água'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Entupimento de pia, mictório ou vaso', 'Manutenção Corretiva Hidráulica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Entupimento de pia, mictório ou vaso'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Higienização dos bebedouros', 'Manutenção Corretiva Hidráulica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Higienização dos bebedouros'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Obstrução de caixa de esgoto', 'Manutenção Corretiva Hidráulica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Obstrução de caixa de esgoto'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Outros', 'Manutenção Corretiva Hidráulica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Outros'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Registro com defeito', 'Manutenção Corretiva Hidráulica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Registro com defeito'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Vazamento em tubulação', 'Manutenção Corretiva Hidráulica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Vazamento em tubulação'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Vazamento em válvula de descarga', 'Manutenção Corretiva Hidráulica'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Vazamento em válvula de descarga'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Poda de árvore ou arbusto', 'Manutenção Corretiva Jardinagem'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'JARDINAGEM'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Poda de árvore ou arbusto'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Retirada de vegetação (ervas daninhas)', 'Manutenção Corretiva Jardinagem'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'JARDINAGEM'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Retirada de vegetação (ervas daninhas)'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Manutenção de Alvenaria', 'Manutenção Civil corretiva'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'MANUTENÇÂO CIVIL'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Manutenção de Alvenaria'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Outros', 'Manutenção Civil corretiva'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'MANUTENÇÂO CIVIL'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Outros'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Reparo de pisos e revestimentos', 'Manutenção Civil corretiva'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'MANUTENÇÂO CIVIL'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Reparo de pisos e revestimentos'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Novo Projeto ou Readequação de Área', 'Demanda personalizada'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Novo Projeto ou Readequação de Área'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Solicitação de Recursos Diversos', 'Demanda personalizada'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Solicitação de Recursos Diversos'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'Pintura de segurança/operacional/predial/metálica', 'Manutenção Preventiva Pintura de Sinalização'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'Pintura de segurança/operacional/predial/metálica'
  );

INSERT INTO SERVICE_TYPE
    (ID_SERVICE_CATEGORY, NAME, DESCRIPTION)
SELECT SC.ID, 'TESTE Pintura', 'Manutenção Preventiva Pintura de Sinalização'
FROM SERVICE_CATEGORY SC
WHERE SC.NAME = 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_TYPE ST
      WHERE ST.ID_SERVICE_CATEGORY = SC.ID
        AND ST.NAME = 'TESTE Pintura'
  );
