-- ================================================================
-- SERVICE_FIELD_TYPE
-- ================================================================
-- ARTÍFICE > Fixação de Placas/Quadros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Referência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Fixação de Placas/Quadros'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Referência'
  );

-- ARTÍFICE > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Outros'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

-- ARTÍFICE > Regulagem de porta
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Regulagem de porta'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Problema identificado', 'MULTI_SELECT', '["Não fecha", "Desalinhada", "outro", "Não abre bem"]'::JSONB,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Regulagem de porta'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Problema identificado'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Tipo da porta', 'SINGLE_SELECT', '["Madeira", "Corta-fogo", "Vidro", "Metálica"]'::JSONB,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Regulagem de porta'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Tipo da porta'
  );

-- ARTÍFICE > Reparos em móveis
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Reparos em móveis'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

-- ARTÍFICE > Substituição de dispenser (papel higiênico, papel toalha ou sabão)
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Substituição de dispenser (papel higiênico, papel toalha ou sabão)'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Tipo do dispenser', 'SINGLE_SELECT', '["Papel higiênico", "Sabão", "Papel toalha"]'::JSONB,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Substituição de dispenser (papel higiênico, papel toalha ou sabão)'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Tipo do dispenser'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Motivo', 'SINGLE_SELECT', '["Outro", "Quebrado", "Não fixa na parede"]'::JSONB,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Substituição de dispenser (papel higiênico, papel toalha ou sabão)'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Motivo'
  );

-- ARTÍFICE > Substituição de fitas de demarcação lisa/antiderrapante
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Substituição de fitas de demarcação lisa/antiderrapante'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Observações', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Substituição de fitas de demarcação lisa/antiderrapante'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Observações'
  );

-- ARTÍFICE > Substituição de tampa de vaso sanitário
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Substituição de tampa de vaso sanitário'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Observações', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Substituição de tampa de vaso sanitário'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Observações'
  );

-- ARTÍFICE > Troca de fechadura/miolo
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Troca de fechadura/miolo'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Observações', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Troca de fechadura/miolo'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Observações'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Motivo da troca', 'SINGLE_SELECT', '["Outro", "Danificada", "Chave perdida"]'::JSONB,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Troca de fechadura/miolo'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Motivo da troca'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Observações da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 4
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'ARTÍFICE'
  AND ST.NAME = 'Troca de fechadura/miolo'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Observações da ocorrência'
  );

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento com avaria evidente
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Equipamento com avaria evidente'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Equipamento com avaria evidente'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quase sempre visíveis (exemplo ar-57)'
  );

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento não liga
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Equipamento não liga'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Equipamento não liga'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quase sempre visíveis (exemplo ar-57)'
  );

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento não refrigera/climatiza
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Equipamento não refrigera/climatiza'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Equipamento não refrigera/climatiza'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quase sempre visíveis (exemplo ar-57)'
  );

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Instalação de equipamento
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Instalação de equipamento'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Técnico responsável', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Instalação de equipamento'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Técnico responsável'
  );

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Outros'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Remanejamento de unidade evaporadora/condensadora
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Remanejamento de unidade evaporadora/condensadora'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Remanejamento de unidade evaporadora/condensadora'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quase sempre visíveis (exemplo ar-57)'
  );

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Vazamento de água em equipamento
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quase sempre visível (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Vazamento de água em equipamento'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quase sempre visível (exemplo ar-57)'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
  AND ST.NAME = 'Vazamento de água em equipamento'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

-- COPA > Limpeza de geladeira ou micro-ondas
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Equipamento que necessita limpeza', 'MULTI_SELECT', '["Microondas", "Geladeira"]'::JSONB,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'COPA'
  AND ST.NAME = 'Limpeza de geladeira ou micro-ondas'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Equipamento que necessita limpeza'
  );

-- Dúvida Aplicativo > Dificuldade com a reserva
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Está tendo dificuldade em fazer a reserva?', 'BOOL', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'Dúvida Aplicativo'
  AND ST.NAME = 'Dificuldade com a reserva'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Está tendo dificuldade em fazer a reserva?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Descreva a situação?', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'Dúvida Aplicativo'
  AND ST.NAME = 'Dificuldade com a reserva'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Descreva a situação?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Caso esteja aparecendo algum erro, envie o print da tela', 'TEXT', NULL,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'Dúvida Aplicativo'
  AND ST.NAME = 'Dificuldade com a reserva'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Caso esteja aparecendo algum erro, envie o print da tela'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Está conforme?', 'TEXT', NULL,
       TRUE, TRUE, 4
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'Dúvida Aplicativo'
  AND ST.NAME = 'Dificuldade com a reserva'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Está conforme?'
  );

-- INSTALAÇÕES ELÉTRICAS > Interruptor ou Tomada com defeito/quebrado
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Interruptor ou Tomada com defeito/quebrado'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Tet', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Interruptor ou Tomada com defeito/quebrado'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Tet'
  );

-- INSTALAÇÕES ELÉTRICAS > Lâmpadas queimadas
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Lâmpadas queimadas'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Qual o seu problema?', 'SINGLE_SELECT', '["Lâmpada/refletor queimada", "Problema no interruptor"]'::JSONB,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Lâmpadas queimadas'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Qual o seu problema?'
  );

-- INSTALAÇÕES ELÉTRICAS > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Outros'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

-- INSTALAÇÕES ELÉTRICAS > Quadro elétrico desarmando
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Quadro elétrico desarmando'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

-- INSTALAÇÕES ELÉTRICAS > Regularização de extensões/plugs/equipamentos
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Regularização de extensões/plugs/equipamentos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Tipo de item', 'SINGLE_SELECT', '["Equipamento elétrico", "Plug"]'::JSONB,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Regularização de extensões/plugs/equipamentos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Tipo de item'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quantidade de itens', 'NUMBER', NULL,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Regularização de extensões/plugs/equipamentos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quantidade de itens'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Risco identificado', 'TEXT', NULL,
       TRUE, TRUE, 4
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Regularização de extensões/plugs/equipamentos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Risco identificado'
  );

-- INSTALAÇÕES ELÉTRICAS > Substituição de biruta
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Substituição de biruta'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quantidade', 'NUMBER', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Substituição de biruta'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quantidade'
  );

-- INSTALAÇÕES ELÉTRICAS > Tomada com defeito/quebrada
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Motivo', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Tomada com defeito/quebrada'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Motivo'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quantidade', 'NUMBER', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Tomada com defeito/quebrada'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quantidade'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Tipo de tomada', 'TEXT', NULL,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES ELÉTRICAS'
  AND ST.NAME = 'Tomada com defeito/quebrada'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Tipo de tomada'
  );

-- INSTALAÇÕES HIDRÁULICAS > Ambiente sem água
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Tipo de ponto afetado', 'SINGLE_SELECT', '["OUTRO", "VASO SANITARIO"]'::JSONB,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Ambiente sem água'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Tipo de ponto afetado'
  );

-- INSTALAÇÕES HIDRÁULICAS > Entupimento de pia, mictório ou vaso
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Entupimento de pia, mictório ou vaso'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Ponto afetado', 'SINGLE_SELECT', '["Mictório", "Outro", "Vaso sanitário"]'::JSONB,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Entupimento de pia, mictório ou vaso'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Ponto afetado'
  );

-- INSTALAÇÕES HIDRÁULICAS > Higienização dos bebedouros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Higienização dos bebedouros'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quantidade de bebedouro', 'NUMBER', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Higienização dos bebedouros'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quantidade de bebedouro'
  );

-- INSTALAÇÕES HIDRÁULICAS > Obstrução de caixa de esgoto
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Obstrução identificada', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Obstrução de caixa de esgoto'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Obstrução identificada'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Quantidade de caixas', 'NUMBER', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Obstrução de caixa de esgoto'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Quantidade de caixas'
  );

-- INSTALAÇÕES HIDRÁULICAS > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Outros'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto da necessidade'
  );

-- INSTALAÇÕES HIDRÁULICAS > Registro com defeito
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Registro com defeito'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Problema identificado', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Registro com defeito'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Problema identificado'
  );

-- INSTALAÇÕES HIDRÁULICAS > Vazamento em tubulação
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Itensidade', 'SINGLE_SELECT', '["FLUXO CONTÍNUO", "GOTEJAMENTO"]'::JSONB,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Vazamento em tubulação'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Itensidade'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Vazamento em tubulação'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto'
  );

-- INSTALAÇÕES HIDRÁULICAS > Vazamento em válvula de descarga
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Frequencia do vazamento', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'INSTALAÇÕES HIDRÁULICAS'
  AND ST.NAME = 'Vazamento em válvula de descarga'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Frequencia do vazamento'
  );

-- JARDINAGEM > Poda de árvore ou arbusto
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Insira imagem', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'JARDINAGEM'
  AND ST.NAME = 'Poda de árvore ou arbusto'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Insira imagem'
  );

-- JARDINAGEM > Retirada de vegetação (ervas daninhas)
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Área aproximada afetada (metros quadrados)', 'NUMBER', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'JARDINAGEM'
  AND ST.NAME = 'Retirada de vegetação (ervas daninhas)'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Área aproximada afetada (metros quadrados)'
  );

-- MANUTENÇÂO CIVIL > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Foto/anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'MANUTENÇÂO CIVIL'
  AND ST.NAME = 'Outros'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Foto/anexo da ocorrência'
  );

-- MANUTENÇÂO CIVIL > Reparo de pisos e revestimentos
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'MANUTENÇÂO CIVIL'
  AND ST.NAME = 'Reparo de pisos e revestimentos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Anexo da ocorrência'
  );

-- NOVOS PROJETOS > Novo Projeto ou Readequação de Área
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Setor demandante', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Novo Projeto ou Readequação de Área'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Setor demandante'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Projeto ou readequação de área', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Novo Projeto ou Readequação de Área'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Projeto ou readequação de área'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Número da pt e/ou apr', 'TEXT', NULL,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Novo Projeto ou Readequação de Área'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Número da pt e/ou apr'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Registros', 'TEXT', NULL,
       TRUE, TRUE, 4
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Novo Projeto ou Readequação de Área'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Registros'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Tempo', 'TEXT', NULL,
       TRUE, TRUE, 5
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Novo Projeto ou Readequação de Área'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Tempo'
  );

-- NOVOS PROJETOS > Solicitação de Recursos Diversos
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'O que será realizado?', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'O que será realizado?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Onde será realizado?', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Onde será realizado?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Há necessidade de artificies ?', 'BOOL', NULL,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Há necessidade de artificies ?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'qual o nível urgência?', 'TEXT', NULL,
       TRUE, TRUE, 4
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'qual o nível urgência?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Envolve instalações/modificações elétricas ?', 'BOOL', NULL,
       TRUE, TRUE, 5
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Envolve instalações/modificações elétricas ?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Envolve instalações/modificações hidráulicas ?', 'BOOL', NULL,
       TRUE, TRUE, 6
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Envolve instalações/modificações hidráulicas ?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Envolve instalações/modificações de refirgeração ?', 'BOOL', NULL,
       TRUE, TRUE, 7
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Envolve instalações/modificações de refirgeração ?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Há necessidade de materiais de pintura ?', 'BOOL', NULL,
       TRUE, TRUE, 8
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Há necessidade de materiais de pintura ?'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Se houver documentos do projeto anexar', 'TEXT', NULL,
       TRUE, TRUE, 9
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'NOVOS PROJETOS'
  AND ST.NAME = 'Solicitação de Recursos Diversos'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Se houver documentos do projeto anexar'
  );

-- PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA > Pintura de segurança/operacional/predial/metálica
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Observações', 'TEXT', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
  AND ST.NAME = 'Pintura de segurança/operacional/predial/metálica'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Observações'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Pintura', 'SINGLE_SELECT', '["Outros", "Faixa de pedestre"]'::JSONB,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
  AND ST.NAME = 'Pintura de segurança/operacional/predial/metálica'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Pintura'
  );

-- PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA > TESTE Pintura
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Possui pt vinculada', 'BOOL', NULL,
       TRUE, TRUE, 1
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
  AND ST.NAME = 'TESTE Pintura'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Possui pt vinculada'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Tipo de pintura', 'TEXT', NULL,
       TRUE, TRUE, 2
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
  AND ST.NAME = 'TESTE Pintura'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Tipo de pintura'
  );

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
SELECT ST.ID, 'Data de finalização', 'DATE', NULL,
       TRUE, TRUE, 3
FROM SERVICE_TYPE ST
JOIN SERVICE_CATEGORY SC
  ON SC.ID = ST.ID_SERVICE_CATEGORY
WHERE SC.NAME = 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
  AND ST.NAME = 'TESTE Pintura'
  AND NOT EXISTS (
      SELECT 1 FROM SERVICE_FIELD_TYPE SFT
      WHERE SFT.ID_SERVICE_TYPE = ST.ID
        AND SFT.NAME = 'Data de finalização'
  );

COMMIT;