-- =========================
-- SERVICE_TYPE
-- =========================

-----Categoria Artifice----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (1, 1, 'Reparos em móveis');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (2, 1, 'Fixação de Placas/Quadros');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (3, 1, 'Substituição de tampa de vaso sanitário');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (4, 1, 'Substituição de dispenser (papel higiênico, papel toalha ou sabão)');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (5, 1, 'Regulagem de porta');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (6, 1, 'Outros');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (7, 1, 'Substituição de fitas de demarcação lisa/antiderrapante');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (23, 1, 'Troca de fechadura/miolo');

-----Categoria INSTALAÇÕES ELÉTRICAS----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (5, 7, 'Interruptor ou Tomada com defeito/quebrado');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (17, 7, 'Regularização de extensões/plugs/equipamentos');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (18, 7, 'Lâmpadas queimadas');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (19, 7, 'Substituição de biruta');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (20, 7, 'Quadro elétrico desarmando');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (26, 7, 'Outros');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (32, 7, 'Tomada com defeito/quebrada');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (33, 7, 'Montagem de infraestrutura elétrica');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (36, 7, 'Remoção ou Instalação de ponto de tomada');

-----Categoria INSTALAÇÕES HIDRÁULICAS----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (21, 6, 'Vazamento em tubulação');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (11, 6, 'Ambiente sem água');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (12, 6, 'Registro com defeito');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (40, 6, 'Obstrução de caixa de esgoto');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (49, 6, 'Vazamento em válvula de descarga');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (15, 6, 'Higienização dos bebedouros');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (7, 6, 'Entupimento de pia, mictório ou vaso');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (25, 6, 'Outros');

----Dúvida Aplicativo---
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (4, 4, 'Dificuldade com a reserva');

-----Categoria COPA-----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (3, 3, 'Limpeza de geladeira ou micro-ondas');

-----Categoria NOVOS PROJETOS----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (6, 5, 'Novo Projeto ou Readequação de Área');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (14, 5, 'Solicitação de Recursos Diversos');

-----Categoria JARDINAGEM----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (43, 11, 'Retirada de vegetação (ervas daninhas)');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (47, 11, 'Poda de árvore ou arbusto');

-----Categoria MANUTENÇÂO CIVIL----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (30, 9, 'Reparo de pisos e revestimentos');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (45, 9, 'Outros');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (46, 9, 'Manutenção de Alvenaria');

-----Categoria CLIMATIZAÇÃO E REFRIGERAÇÃO----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (22, 8, 'Outros');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (24, 8, 'Vazamento de água em equipamento');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (27, 8, 'Equipamento não liga');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (28, 8, 'Equipamento não refrigera/climatiza');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (29, 8, 'Remanejamento de unidade evaporadora/condensadora');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (44, 8, 'Equipamento com avaria evidente');

-----Categoria PMOC----
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (34, 10, 'PMOC SEMESTRAL');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (35, 10, 'PMOC MENSAL Cortina de ar');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (39, 10, 'PMOC BIMESTRAL');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (41, 10, 'PMOC TRIMESTRAL');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (42, 10, 'PMOC ANUAL');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (31, 10, 'PMOC MENSAL');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (48, 10, 'PMOC SEMESTRAL Cortina de ar');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (50, 10, 'PMOC BIMESTRAL Cortina de ar');

--- PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA ---
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (2, 2, 'TESTE Pintura');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (37, 2, 'Pintura de segurança/operacional/predial/metálica');
INSERT INTO SERVICE_TYPE (ID, SERVICE_CATEGORY_ID, NAME) VALUES (51, 2, 'Outros');
