-- Confere totais e avança identities sem DDL nem commit intermediário.
DECLARE
    n NUMBER;
    seq_name VARCHAR2(128);
    increment_value NUMBER;
    next_id NUMBER;
BEGIN
    SELECT COUNT(*) INTO n FROM OHFC_SLA;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_SLA'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_SERVICE_CATEGORY;
    IF n <> 9 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_SERVICE_CATEGORY'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_SERVICE_CATEGORY' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 10;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_SECTOR;
    IF n <> 12 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_SECTOR'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_SECTOR' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 12;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_MEMBERSHIP;
    IF n <> 99 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_MEMBERSHIP'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_MEMBERSHIP' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 99;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_BUSINESS;
    IF n <> 2 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_BUSINESS'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_BUSINESS' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 2;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_REQUEST_TYPE;
    IF n <> 2 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REQUEST_TYPE'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_REQUEST_TYPE' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 2;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_REQUEST_STATUS;
    IF n <> 5 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REQUEST_STATUS'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_REQUEST_STATUS' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 5;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_REQUEST_TRANSACTION_STATUS;
    IF n <> 4 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REQUEST_TRANSACTION_STATUS'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_REQUEST_TRANSACTION_STATUS' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 4;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_SERVICE_TYPE;
    IF n <> 51 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_SERVICE_TYPE'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_SERVICE_TYPE' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 51;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_SERVICE_FIELD_TYPE;
    IF n <> 165 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_SERVICE_FIELD_TYPE'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_SERVICE_FIELD_TYPE' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 165;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_REGION;
    IF n <> 9 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REGION'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_REGION' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 9;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_LOCATION;
    IF n <> 67 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_LOCATION'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_LOCATION' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 67;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_REQUEST;
    IF n <> 1675 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REQUEST'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_REQUEST' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 1687;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_SERVICE_FIELD_VALUE;
    IF n <> 1208 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_SERVICE_FIELD_VALUE'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_SERVICE_FIELD_VALUE' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 1208;
    END LOOP;
    SELECT COUNT(*) INTO n FROM OHFC_SERVICE_FIELD_MEDIA;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_SERVICE_FIELD_MEDIA'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_REQUEST_TASK;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REQUEST_TASK'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_TASK_MEMBER_OCCURRENCE;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_TASK_MEMBER_OCCURRENCE'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_REQUEST_TASK_MEDIA;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REQUEST_TASK_MEDIA'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_REQUEST_TRANSACTION;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REQUEST_TRANSACTION'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_CHECKLIST_TYPE;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_CHECKLIST_TYPE'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_CHECKLIST_FIELD_TYPE;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_CHECKLIST_FIELD_TYPE'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_REQUEST_TASK_CHECKLIST;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_REQUEST_TASK_CHECKLIST'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_CHECKLIST_FIELD_VALUE;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_CHECKLIST_FIELD_VALUE'); END IF;
END;
/
COMMIT;
