-- ============================================================
-- OpsHub / SolicitacoesHub - Schema unificado PostgreSQL
-- Arquivos comparados:
-- 1) create_solicitacoeshub_schema.sql
-- 2) Create_Tables.sql
--
-- Observacao:
-- Script consolidado removendo duplicidades e mantendo as tabelas
-- presentes no diagrama completo, incluindo campos dinamicos.
-- ============================================================

BEGIN;

-- ============================================================
-- Remocao das tabelas respeitando dependencias
-- ============================================================

DROP TABLE IF EXISTS task_member_occurrence CASCADE;
DROP TABLE IF EXISTS membership CASCADE;
DROP TABLE IF EXISTS request_task CASCADE;
DROP TABLE IF EXISTS service_fields_values CASCADE;
DROP TABLE IF EXISTS request_aprove CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS service_fields_types CASCADE;
DROP TABLE IF EXISTS service_type CASCADE;
DROP TABLE IF EXISTS service_category CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS regions CASCADE;
DROP TABLE IF EXISTS business CASCADE;
DROP TABLE IF EXISTS requests_types CASCADE;
DROP TABLE IF EXISTS REQUEST_STATUS CASCADE;
DROP TABLE IF EXISTS sector CASCADE;

-- ============================================================
-- Tabelas de setor                                          
-- ============================================================

CREATE TABLE sector (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_sector_name UNIQUE (name)
);

-- ============================================================
-- Tabelas de Tipo de solicitação (Chamado, Atividade de Patio)                                          
-- ============================================================

CREATE TABLE requests_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_requests_types_name UNIQUE (name)
);

-- ============================================================
-- Tabelas de opções de status da Solicitçaão de atividade  
-- (Solicitado, Aprovado, Reprovado, Reprovado->Data alterada, Conluido) 
-- ============================================================

CREATE TABLE REQUEST_STATUS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(30) NOT NULL,

    CONSTRAINT uq_status_description UNIQUE (description)
);

-- ============================================================
-- Tabelas de Unidades de negocio (Tecon, CLS, outros)
-- ============================================================

CREATE TABLE business (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,

    CONSTRAINT uq_business_name UNIQUE (name)
);



-- ============================================================
-- Tabela de Regiões
-- (Prédio ADM, Armazem, Almoxarifado, Pátio Operacional)
-- ============================================================

CREATE TABLE regions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_business INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),

    CONSTRAINT fk_regions_business
        FOREIGN KEY (id_business)
        REFERENCES business (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_regions_business_name UNIQUE (id_business, name)
);

-- ============================================================
-- Tabela de Localizações ()
-- ============================================================

CREATE TABLE locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),
    location_x DECIMAL(10,8),
    location_y DECIMAL(11,8),

    CONSTRAINT fk_locations_regions
        FOREIGN KEY (id_region)
        REFERENCES regions (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_locations_region_name UNIQUE (id_region, name)
);

-- ============================================================
-- Tabela de categorias de serviços
-- ============================================================

CREATE TABLE service_category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_service_category_name UNIQUE (name)
);

-- ============================================================
-- Tabela de tipos de servico e campos dinamicos
-- ============================================================

CREATE TABLE service_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service_category INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),

    CONSTRAINT fk_service_type_service_category
        FOREIGN KEY (id_service_category)
        REFERENCES service_category (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_service_type_category_name UNIQUE (id_service_category, name)
);

-- ============================================================
-- Tabela de campos dinamicos para os service_types
-- ============================================================

CREATE TABLE service_fields_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service_type INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50),
    options JSONB,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER,

    CONSTRAINT fk_service_fields_types_service_type
        FOREIGN KEY (id_service_type)
        REFERENCES service_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_service_fields_types_service_name UNIQUE (id_service_type, name)
);

-- ============================================================
-- Solicitacoes
-- ============================================================

CREATE TABLE requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request_type INTEGER NOT NULL,
    id_sector_requester INTEGER NOT NULL,
    id_sector_responsible INTEGER,
    id_location INTEGER,
    id_service_type INTEGER NOT NULL,
    id_status INTEGER NOT NULL,
    occurrence_datetime TIMESTAMP,
    planned_datetime TIMESTAMP,
    images_endpoint VARCHAR(200),
    description VARCHAR(200),

    CONSTRAINT fk_requests_requests_types
        FOREIGN KEY (id_request_type)
        REFERENCES requests_types (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_sector_requester
        FOREIGN KEY (id_sector_requester)
        REFERENCES sector (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_sector_responsible
        FOREIGN KEY (id_sector_responsible)
        REFERENCES sector (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_locations
        FOREIGN KEY (id_location)
        REFERENCES locations (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_service_type
        FOREIGN KEY (id_service_type)
        REFERENCES service_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_status
        FOREIGN KEY (id_status)
        REFERENCES status (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE service_fields_values (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service_field_types INTEGER NOT NULL,
    id_request INTEGER NOT NULL,
    value JSONB,

    CONSTRAINT fk_service_fields_values_field_type
        FOREIGN KEY (id_service_field_types)
        REFERENCES service_fields_types (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_service_fields_values_request
        FOREIGN KEY (id_request)
        REFERENCES requests (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_service_fields_values_request_field UNIQUE (id_request, id_service_field_types)
);

-- ============================================================
-- Atividades / visitas e executantes
-- ============================================================

CREATE TABLE request_task (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request INTEGER NOT NULL,
    start_datetime TIMESTAMP,
    stop_datetime TIMESTAMP,
    description VARCHAR(100),

    CONSTRAINT fk_request_task_request
        FOREIGN KEY (id_request)
        REFERENCES requests (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Tabela indicada no diagrama como ja existente no ADMSCOL.
-- Mantida aqui apenas para representar o relacionamento usado pelo modelo.
-- A coluna idmembership nao recebeu FK porque a tabela externa nao aparece no diagrama.
CREATE TABLE membership (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request INTEGER,
    idmembership INTEGER,

    CONSTRAINT fk_membership_request
        FOREIGN KEY (id_request)
        REFERENCES requests (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE task_member_occurrence (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_task INTEGER NOT NULL,
    id_membership INTEGER NOT NULL,

    CONSTRAINT fk_task_member_occurrence_task
        FOREIGN KEY (id_task)
        REFERENCES request_task (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_task_member_occurrence_membership
        FOREIGN KEY (id_membership)
        REFERENCES membership (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_task_member_occurrence UNIQUE (id_task, id_membership)
);

-- ============================================================
-- Aprovacao de solicitacoes
-- ============================================================

CREATE TABLE request_aprove (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request INTEGER NOT NULL,
    id_sector_responsible INTEGER,
    id_batch INTEGER,
    id_service_type INTEGER,
    planned_datetime TIMESTAMP,
    description VARCHAR(100),

    CONSTRAINT fk_request_aprove_requests
        FOREIGN KEY (id_request)
        REFERENCES requests (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_request_aprove_sector_responsible
        FOREIGN KEY (id_sector_responsible)
        REFERENCES sector (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_request_aprove_service_type
        FOREIGN KEY (id_service_type)
        REFERENCES service_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT

    -- id_batch ficou sem FK porque o diagrama nao apresenta tabela BATCH.
    -- No arquivo Create_Tables.sql ele apontava para locations(id), mas isso parece inconsistente.
);

-- ============================================================
-- Indices para chaves estrangeiras e consultas frequentes
-- ============================================================

CREATE INDEX idx_regions_id_business ON regions (id_business);
CREATE INDEX idx_locations_id_region ON locations (id_region);
CREATE INDEX idx_service_type_id_service_category ON service_type (id_service_category);
CREATE INDEX idx_service_fields_types_id_service_type ON service_fields_types (id_service_type);

CREATE INDEX idx_requests_id_request_type ON requests (id_request_type);
CREATE INDEX idx_requests_id_sector_requester ON requests (id_sector_requester);
CREATE INDEX idx_requests_id_sector_responsible ON requests (id_sector_responsible);
CREATE INDEX idx_requests_id_location ON requests (id_location);
CREATE INDEX idx_requests_id_service_type ON requests (id_service_type);
CREATE INDEX idx_requests_id_status ON requests (id_status);
CREATE INDEX idx_requests_planned_datetime ON requests (planned_datetime);
CREATE INDEX idx_requests_occurrence_datetime ON requests (occurrence_datetime);

CREATE INDEX idx_service_fields_values_id_field_type ON service_fields_values (id_service_field_types);
CREATE INDEX idx_service_fields_values_id_request ON service_fields_values (id_request);

CREATE INDEX idx_request_task_id_request ON request_task (id_request);
CREATE INDEX idx_membership_id_request ON membership (id_request);
CREATE INDEX idx_task_member_occurrence_id_task ON task_member_occurrence (id_task);
CREATE INDEX idx_task_member_occurrence_id_membership ON task_member_occurrence (id_membership);

CREATE INDEX idx_request_aprove_id_request ON request_aprove (id_request);
CREATE INDEX idx_request_aprove_id_sector_responsible ON request_aprove (id_sector_responsible);
CREATE INDEX idx_request_aprove_id_batch ON request_aprove (id_batch);
CREATE INDEX idx_request_aprove_id_service_type ON request_aprove (id_service_type);

-- ============================================================
-- Cargas iniciais sugeridas
-- ============================================================

COMMIT;
