-- ============================================================
-- Tabelas de Unidades de negocio (Tecon, CLS, outros)
-- ============================================================

CREATE TABLE business (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,

    CONSTRAINT uq_business_name UNIQUE (name)
);
-- ============================================================
-- Tabela de Regiões
-- (Prédio ADM, Armazem, Almoxarifado, Pátio Operacional)
-- ============================================================

CREATE TABLE region (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_business INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),

    CONSTRAINT fk_region_business
        FOREIGN KEY (id_business)
        REFERENCES business (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_region_business_name UNIQUE (id_business, name)
);

-- ============================================================
-- Tabela de Localizações ()
-- ============================================================

CREATE TABLE locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),
    location_x DECIMAL(10,8),
    location_y DECIMAL(11,8),

    CONSTRAINT fk_locations_region
        FOREIGN KEY (id_region)
        REFERENCES region (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_locations_region_name UNIQUE (id_region, name)
);