-- ============================================================
-- SCHEMA: SISTEMA DE SOLICITAÇÕES, CHAMADOS E ATIVIDADES
-- BANCO DE DADOS: POSTGRESQL
-- ============================================================


-- ============================================================
-- 1. TABELA BUSINESS
-- ============================================================

CREATE TABLE BUSINESS
(
    ID      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME    VARCHAR(30),

    CONSTRAINT PK_BUSINESS
        PRIMARY KEY (ID)
);


-- ============================================================
-- 2. TABELA REGION
-- ============================================================

CREATE TABLE REGION
(
    ID              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_BUSINESS     INTEGER,
    NAME            VARCHAR(100),

    CONSTRAINT PK_REGION
        PRIMARY KEY (ID)
);


-- ============================================================
-- 3. TABELA LOCATION
-- ============================================================

CREATE TABLE LOCATION
(
    ID              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_REGION       INTEGER,
    NAME            VARCHAR(100),
    LOCATION_X      DECIMAL(10,8),
    LOCATION_Y      DECIMAL(11,8),

    CONSTRAINT PK_LOCATION
        PRIMARY KEY (ID)
);


-- ============================================================
-- 4. TABELA REQUEST_STATUS
-- ============================================================

CREATE TABLE REQUEST_STATUS
(
    ID              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    DESCRIPTION     VARCHAR(30),

    CONSTRAINT PK_REQUEST_STATUS
        PRIMARY KEY (ID)
);


-- ============================================================
-- 5. TABELA REQUEST_TYPE
-- Indica se uma solicitação é um chamado
-- ou uma atividade de pátio.
-- ============================================================

CREATE TABLE REQUEST_TYPE
(
    ID      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME    VARCHAR(30),

    CONSTRAINT PK_REQUEST_TYPE
        PRIMARY KEY (ID)
);


-- ============================================================
-- 6. TABELA TRANSACTION_STATUS
-- ============================================================

CREATE TABLE TRANSACTION_STATUS
(
    ID              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    DESCRIPTION     VARCHAR(30),

    CONSTRAINT PK_TRANSACTION_STATUS
        PRIMARY KEY (ID)
);


-- ============================================================
-- 7. TABELA SERVICE_CATEGORY
-- ============================================================

CREATE TABLE SERVICE_CATEGORY
(
    ID      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME    VARCHAR(100),

    CONSTRAINT PK_SERVICE_CATEGORY
        PRIMARY KEY (ID)
);


-- ============================================================
-- 8. TABELA SERVICE_TYPE
-- ============================================================

CREATE TABLE SERVICE_TYPE
(
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_SERVICE_CATEGORY     INTEGER,
    NAME                    VARCHAR(100),
    DESCRIPTION             VARCHAR(100),

    CONSTRAINT PK_SERVICE_TYPE
        PRIMARY KEY (ID)
);


-- ============================================================
-- 9. TABELA SERVICE_FIELD_TYPE
-- Define os possíveis campos de cada tipo de chamado.
-- ============================================================

CREATE TABLE SERVICE_FIELD_TYPE
(
    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_SERVICE_TYPE     INTEGER,
    NAME                VARCHAR(100),
    TYPE                VARCHAR(50),
    OPTIONS             JSONB,
    REQUIRED            BOOLEAN,
    ACTIVE              BOOLEAN,
    DISPLAY_ORDER       INTEGER,

    CONSTRAINT PK_SERVICE_FIELDS_TYPE
        PRIMARY KEY (ID)
);


-- ============================================================
-- 10. TABELA SECTOR
-- ============================================================

CREATE TABLE SECTOR
(
    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME                VARCHAR(100),
    ACCESS_LEVELS       INTEGER,

    CONSTRAINT PK_SECTOR
        PRIMARY KEY (ID)
);


-- ============================================================
-- 11. TABELA MEMBERSHIP
-- Membros internos referenciados por solicitações,
-- tarefas, transações e associações de setor.
-- ============================================================

CREATE TABLE MEMBERSHIP
(
    ID      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME    VARCHAR(300),
    EMAIL   VARCHAR(300),

    CONSTRAINT PK_MEMBERSHIP
        PRIMARY KEY (ID)
);


-- ============================================================
-- 12. TABELA REQUEST
-- Tabela principal de solicitações, chamados e atividades.
-- ============================================================

CREATE TABLE REQUEST
(
    ID                      INTEGER GENERATED BY DEFAULT AS IDENTITY,

    ID_REQUEST_TYPE         INTEGER,
    ID_MEMBER_REQUESTER     INTEGER,
    ID_MEMBER_RESPONDER     INTEGER,
    ID_LOCATION             INTEGER,
    ID_SERVICE_TYPE         INTEGER,
    ID_REQUEST_STATUS       INTEGER,

    CREATED_DATE            TIMESTAMP,
    AGREED_DATE             TIMESTAMP,
    STARTED_DATE            TIMESTAMP,
    FINISHED_DATE           TIMESTAMP,
    CANCELED_DATE           TIMESTAMP,

    DESCRIPTION             VARCHAR(300),

    CONSTRAINT PK_REQUEST
        PRIMARY KEY (ID)
);


-- ============================================================
-- 13. TABELA REQUEST_TASK
-- Representa as visitas ou atividades executadas
-- dentro de uma solicitação.
-- ============================================================

CREATE TABLE REQUEST_TASK
(
    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_REQUEST          INTEGER,

    START_DATETIME      TIMESTAMP,
    STOP_DATETIME       TIMESTAMP,

    DESCRIPTION         VARCHAR(100),

    CONSTRAINT PK_REQUEST_TASK
        PRIMARY KEY (ID)
);


-- ============================================================
-- 14. TABELA TASK_MEMBER_OCCURRENCE
-- Tabela associativa entre tarefas e membros executantes.
-- ============================================================

CREATE TABLE TASK_MEMBER_OCCURRENCE
(
    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_TASK             INTEGER,
    ID_MEMBERSHIP       INTEGER,

    CONSTRAINT PK_TASK_MEMBER_OCCURRENCE
        PRIMARY KEY (ID)
);


-- ============================================================
-- 15. TABELA REQUEST_TRANSACTION
-- Registra propostas, solicitações e movimentações
-- relacionadas a uma REQUEST.
-- ============================================================



-- ============================================================
-- 15. TABELA SERVICE_FIELD_VALUE
-- Armazena os valores preenchidos nos campos dinâmicos
-- de uma solicitação.
-- ============================================================

CREATE TABLE SERVICE_FIELD_VALUE
(
    ID                          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_SERVICE_FIELD_TYPE       INTEGER,
    ID_REQUEST                  INTEGER,
    VALUE                       JSONB,

    CONSTRAINT PK_SERVICE_FIELD_VALUE
        PRIMARY KEY (ID)
);


-- ============================================================
-- 17. TABELA ASSOC_MEMBERSHIP_SECTOR
-- Associação entre membros e setores.
-- ============================================================

CREATE TABLE ASSOC_MEMBERSHIP_SECTOR
(
    ID                  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ID_MEMBER           INTEGER,
    ID_SECTOR_ASSOC     INTEGER,
    ACCESS_LEVEL        INTEGER,

    CONSTRAINT PK_ASSOC_MEMBERSHIP_SECTOR
        PRIMARY KEY (ID)
);


-- ============================================================
-- CHAVES ESTRANGEIRAS
-- ============================================================


-- ============================================================
-- REGION -> BUSINESS
-- ============================================================

ALTER TABLE REGION
    ADD CONSTRAINT FK_REGION_BUSINESS
    FOREIGN KEY (ID_BUSINESS)
    REFERENCES BUSINESS (ID);


-- ============================================================
-- LOCATION -> REGION
-- ============================================================

ALTER TABLE LOCATION
    ADD CONSTRAINT FK_LOCATION_REGION
    FOREIGN KEY (ID_REGION)
    REFERENCES REGION (ID);


-- ============================================================
-- SERVICE_TYPE -> SERVICE_CATEGORY
-- ============================================================

ALTER TABLE SERVICE_TYPE
    ADD CONSTRAINT FK_SERVICE_TYPE_CATEGORY
    FOREIGN KEY (ID_SERVICE_CATEGORY)
    REFERENCES SERVICE_CATEGORY (ID);


-- ============================================================
-- SERVICE_FIELD_TYPE -> SERVICE_TYPE
-- ============================================================

ALTER TABLE SERVICE_FIELD_TYPE
    ADD CONSTRAINT FK_SERVICE_FIELD_TYPE_SERVICE_TYPE
    FOREIGN KEY (ID_SERVICE_TYPE)
    REFERENCES SERVICE_TYPE (ID);


-- ============================================================
-- REQUEST -> REQUEST_TYPE
-- ============================================================

ALTER TABLE REQUEST
    ADD CONSTRAINT FK_REQUEST_REQUEST_TYPE
    FOREIGN KEY (ID_REQUEST_TYPE)
    REFERENCES REQUEST_TYPE (ID);


-- ============================================================
-- REQUEST -> MEMBERSHIP (SOLICITANTE)
-- ============================================================

ALTER TABLE REQUEST
    ADD CONSTRAINT FK_REQUEST_MEMBER_REQUESTER
    FOREIGN KEY (ID_MEMBER_REQUESTER)
    REFERENCES MEMBERSHIP (ID);


-- ============================================================
-- REQUEST -> MEMBERSHIP (RESPONSÁVEL)
-- ============================================================

ALTER TABLE REQUEST
    ADD CONSTRAINT FK_REQUEST_MEMBER_RESPONDER
    FOREIGN KEY (ID_MEMBER_RESPONDER)
    REFERENCES MEMBERSHIP (ID);


-- ============================================================
-- REQUEST -> LOCATION
-- ============================================================

ALTER TABLE REQUEST
    ADD CONSTRAINT FK_REQUEST_LOCATION
    FOREIGN KEY (ID_LOCATION)
    REFERENCES LOCATION (ID);


-- ============================================================
-- REQUEST -> SERVICE_TYPE
-- ============================================================

ALTER TABLE REQUEST
    ADD CONSTRAINT FK_REQUEST_SERVICE_TYPE
    FOREIGN KEY (ID_SERVICE_TYPE)
    REFERENCES SERVICE_TYPE (ID);


-- ============================================================
-- REQUEST -> REQUEST_STATUS
-- ============================================================

ALTER TABLE REQUEST
    ADD CONSTRAINT FK_REQUEST_REQUEST_STATUS
    FOREIGN KEY (ID_REQUEST_STATUS)
    REFERENCES REQUEST_STATUS (ID);


-- ============================================================
-- REQUEST_TASK -> REQUEST
-- ============================================================

ALTER TABLE REQUEST_TASK
    ADD CONSTRAINT FK_REQUEST_TASK_REQUEST
    FOREIGN KEY (ID_REQUEST)
    REFERENCES REQUEST (ID);


-- ============================================================
-- TASK_MEMBER_OCCURRENCE -> REQUEST_TASK
-- ============================================================

ALTER TABLE TASK_MEMBER_OCCURRENCE
    ADD CONSTRAINT FK_TASK_MEMBER_OCCURRENCE_TASK
    FOREIGN KEY (ID_TASK)
    REFERENCES REQUEST_TASK (ID);


-- ============================================================
-- TASK_MEMBER_OCCURRENCE -> MEMBERSHIP
-- ============================================================

ALTER TABLE TASK_MEMBER_OCCURRENCE
    ADD CONSTRAINT FK_TASK_MEMBER_OCCURRENCE_MEMBERSHIP
    FOREIGN KEY (ID_MEMBERSHIP)
    REFERENCES MEMBERSHIP (ID);


-- ============================================================
-- REQUEST_TRANSACTION -> REQUEST
-- ============================================================

ALTER TABLE REQUEST_TRANSACTION
    ADD CONSTRAINT FK_REQUEST_TRANSACTION_REQUEST
    FOREIGN KEY (ID_REQUEST)
    REFERENCES REQUEST (ID);


-- ============================================================
-- REQUEST_TRANSACTION -> MEMBERSHIP (SOLICITANTE)
-- ============================================================

ALTER TABLE REQUEST_TRANSACTION
    ADD CONSTRAINT FK_REQUEST_TRANSACTION_MEMBER_REQUESTER
    FOREIGN KEY (ID_MEMBER_REQUESTER)
    REFERENCES MEMBERSHIP (ID);


-- ============================================================
-- REQUEST_TRANSACTION -> MEMBERSHIP (RESPONSÁVEL)
-- ============================================================

ALTER TABLE REQUEST_TRANSACTION
    ADD CONSTRAINT FK_REQUEST_TRANSACTION_MEMBER_RESPONDER
    FOREIGN KEY (ID_MEMBER_RESPONDER)
    REFERENCES MEMBERSHIP (ID);


-- ============================================================
-- REQUEST_TRANSACTION -> TRANSACTION_STATUS
-- ============================================================

ALTER TABLE REQUEST_TRANSACTION
    ADD CONSTRAINT FK_REQUEST_TRANSACTION_STATUS
    FOREIGN KEY (ID_TRANSACTION_STATUS)
    REFERENCES TRANSACTION_STATUS (ID);


-- ============================================================
-- SERVICE_FIELD_VALUE -> SERVICE_FIELD_TYPE
-- ============================================================

ALTER TABLE SERVICE_FIELD_VALUE
    ADD CONSTRAINT FK_SERVICE_FIELD_VALUE_FIELD_TYPE
    FOREIGN KEY (ID_SERVICE_FIELD_TYPE)
    REFERENCES SERVICE_FIELD_TYPE (ID);


-- ============================================================
-- SERVICE_FIELD_VALUE -> REQUEST
-- ============================================================

ALTER TABLE SERVICE_FIELD_VALUE
    ADD CONSTRAINT FK_SERVICE_FIELD_VALUE_REQUEST
    FOREIGN KEY (ID_REQUEST)
    REFERENCES REQUEST (ID);


-- ============================================================
-- ASSOC_MEMBERSHIP_SECTOR -> MEMBERSHIP
-- ============================================================

ALTER TABLE ASSOC_MEMBERSHIP_SECTOR
    ADD CONSTRAINT FK_ASSOC_MEMBERSHIP_SECTOR_MEMBER
    FOREIGN KEY (ID_MEMBER)
    REFERENCES MEMBERSHIP (ID);


-- ============================================================
-- ASSOC_MEMBERSHIP_SECTOR -> SECTOR
-- ============================================================

ALTER TABLE ASSOC_MEMBERSHIP_SECTOR
    ADD CONSTRAINT FK_ASSOC_MEMBERSHIP_SECTOR_SECTOR
    FOREIGN KEY (ID_SECTOR_ASSOC)
    REFERENCES SECTOR (ID);
