CREATE TABLE requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request_type INTEGER NOT NULL,
    id_sector_requester INTEGER NOT NULL,
    id_sector_responsible INTEGER,
    id_location INTEGER,
    id_service_type INTEGER NOT NULL,
    id_status INTEGER NOT NULL,
    occurrence_datetime TIMESTAMP,
    planned_datetime TIMESTAMP,
    images_endpoint VARCHAR(200),
    description VARCHAR(200),

    CONSTRAINT fk_requests_requests_types
        FOREIGN KEY (id_request_type)
        REFERENCES requests_types (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_sector_requester
        FOREIGN KEY (id_sector_requester)
        REFERENCES sector (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_sector_responsible
        FOREIGN KEY (id_sector_responsible)
        REFERENCES sector (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_locations
        FOREIGN KEY (id_location)
        REFERENCES locations (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_service_type
        FOREIGN KEY (id_service_type)
        REFERENCES service_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,


    CONSTRAINT fk_requests_status
    FOREIGN KEY (id_status)
    REFERENCES REQUEST_STATUS (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT

);