-- ============================================================
-- Script PostgreSQL - Database OpsHub
-- Geração das tabelas com base na documentação do banco
-- ============================================================

-- Ordem de remoção respeitando dependências
DROP TABLE IF EXISTS request_aprove CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS service_type CASCADE;
DROP TABLE IF EXISTS service_category CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS regions CASCADE;
DROP TABLE IF EXISTS business CASCADE;
DROP TABLE IF EXISTS requests_types CASCADE;
DROP TABLE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS sector CASCADE;

-- ============================================================
-- Tabelas base
-- ============================================================

CREATE TABLE sector (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE requests_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(30) NOT NULL
);

CREATE TABLE business (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE service_category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL
);

-- ============================================================
-- Tabelas dependentes
-- ============================================================

CREATE TABLE regions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_business INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),

    CONSTRAINT fk_regions_business
        FOREIGN KEY (id_business)
        REFERENCES business (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),
    location_x DECIMAL(10,8),
    location_y DECIMAL(11,8),

    CONSTRAINT fk_locations_regions
        FOREIGN KEY (id_region)
        REFERENCES regions (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE service_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service_category INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),

    CONSTRAINT fk_service_type_service_category
        FOREIGN KEY (id_service_category)
        REFERENCES service_category (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sector_requester INTEGER NOT NULL,
    id_sector_responsible INTEGER NOT NULL,
    id_location INTEGER NOT NULL,
    id_request_type INTEGER NOT NULL,
    id_service_type INTEGER NOT NULL,
    id_status INTEGER NOT NULL,
    ocurrence_datetime TIMESTAMP,
    planned_datetime TIMESTAMP,
    images_endpoint VARCHAR(200),
    description VARCHAR(100),

    CONSTRAINT fk_requests_sector_requester
        FOREIGN KEY (id_sector_requester)
        REFERENCES sector (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_sector_responsible
        FOREIGN KEY (id_sector_responsible)
        REFERENCES sector (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_locations
        FOREIGN KEY (id_location)
        REFERENCES locations (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_requests_types
        FOREIGN KEY (id_request_type)
        REFERENCES requests_types (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_service_type
        FOREIGN KEY (id_service_type)
        REFERENCES service_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_requests_status
        FOREIGN KEY (id_status)
        REFERENCES status (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE request_aprove (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request INTEGER NOT NULL,
    id_sector_responsible INTEGER NOT NULL,
    id_batch INTEGER NOT NULL,
    id_service_type INTEGER NOT NULL,
    planned_datetime TIMESTAMP,
    description VARCHAR(100),

    CONSTRAINT fk_request_aprove_requests
        FOREIGN KEY (id_request)
        REFERENCES requests (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_request_aprove_sector_responsible
        FOREIGN KEY (id_sector_responsible)
        REFERENCES sector (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_request_aprove_locations
        FOREIGN KEY (id_batch)
        REFERENCES locations (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_request_aprove_service_type
        FOREIGN KEY (id_service_type)
        REFERENCES service_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ============================================================
-- Índices para melhorar consultas por chaves estrangeiras
-- ============================================================

CREATE INDEX idx_regions_id_business ON regions (id_business);
CREATE INDEX idx_locations_id_region ON locations (id_region);
CREATE INDEX idx_service_type_id_service_category ON service_type (id_service_category);

CREATE INDEX idx_requests_id_sector_requester ON requests (id_sector_requester);
CREATE INDEX idx_requests_id_sector_responsible ON requests (id_sector_responsible);
CREATE INDEX idx_requests_id_location ON requests (id_location);
CREATE INDEX idx_requests_id_request_type ON requests (id_request_type);
CREATE INDEX idx_requests_id_service_type ON requests (id_service_type);
CREATE INDEX idx_requests_id_status ON requests (id_status);
CREATE INDEX idx_requests_planned_datetime ON requests (planned_datetime);

CREATE INDEX idx_request_aprove_id_request ON request_aprove (id_request);
CREATE INDEX idx_request_aprove_id_sector_responsible ON request_aprove (id_sector_responsible);
CREATE INDEX idx_request_aprove_id_batch ON request_aprove (id_batch);
CREATE INDEX idx_request_aprove_id_service_type ON request_aprove (id_service_type);

-- ============================================================
-- Cargas iniciais sugeridas
-- ============================================================

INSERT INTO requests_types (name) VALUES
    ('Chamado'),
    ('Atividade de Pátio');

INSERT INTO status (description) VALUES
    ('Aberto'),
    ('Programada'),
    ('Em andamento'),
    ('Concluída');
