-- Parte 2/3. Execute após INSERT_MEMBERSHIP.sql na mesma sessão/transação.
-- Os dados de origem usados por este arquivo (CREATED_DATE, AGREED_DATE,
-- STARTED_DATE, FINISHED_DATE, CANCELED_DATE, DESCRIPTION e demais campos)
-- vêm da tabela temporária TMP_REQUEST_IMPORT criada e populada na Parte 1.
-- Por isso, este arquivo não é standalone: ele precisa rodar na mesma sessão
-- em que INSERT_MEMBERSHIP.sql foi executado.
DO $$
BEGIN
    IF TO_REGCLASS('pg_temp.tmp_request_import') IS NULL THEN
        RAISE EXCEPTION 'TMP_REQUEST_IMPORT não existe. Execute INSERT_MEMBERSHIP.sql antes de INSERT_REQUEST.sql na mesma sessão/transação.';
    END IF;
END;
$$;

-- ================================================================
-- RESERVA DOS IDs DE REQUEST
-- Como REQUEST.ID é GENERATED BY DEFAULT AS IDENTITY, o script reserva
-- previamente um ID para cada linha importada. Isso permite vincular cada
-- SERVICE_FIELD_VALUE à REQUEST exata, inclusive quando o Número legado
-- está duplicado na origem.
-- ================================================================
UPDATE TMP_REQUEST_IMPORT
   SET ID_REQUEST = nextval(pg_get_serial_sequence('request', 'id'));

-- ================================================================
-- Validações obrigatórias antes do INSERT de REQUEST.
-- Qualquer inconsistência interrompe a transação.
-- ================================================================
DO $$
DECLARE
    V_ERROR_COUNT INTEGER;
BEGIN
    SELECT COUNT(*)
      INTO V_ERROR_COUNT
      FROM TMP_REQUEST_IMPORT
     WHERE ID_REQUEST IS NULL;
    IF V_ERROR_COUNT > 0 THEN
        RAISE EXCEPTION '% solicitações não receberam ID_REQUEST reservado.', V_ERROR_COUNT;
    END IF;

    SELECT COUNT(*)
      INTO V_ERROR_COUNT
      FROM TMP_REQUEST_IMPORT T
      JOIN REQUEST R
        ON R.ID = T.ID_REQUEST;
    IF V_ERROR_COUNT > 0 THEN
        RAISE EXCEPTION '% IDs reservados para REQUEST já existem na tabela.', V_ERROR_COUNT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM REQUEST_TYPE WHERE ID = 1) THEN
        RAISE EXCEPTION 'REQUEST_TYPE.ID=1 não existe.';
    END IF;

    SELECT COUNT(*)
      INTO V_ERROR_COUNT
      FROM (VALUES (1), (3), (4), (5)) AS EXPECTED(ID)
     WHERE NOT EXISTS (
         SELECT 1 FROM REQUEST_STATUS RS WHERE RS.ID = EXPECTED.ID
     );
    IF V_ERROR_COUNT > 0 THEN
        RAISE EXCEPTION '% IDs obrigatórios não existem em REQUEST_STATUS.', V_ERROR_COUNT;
    END IF;

    SELECT COUNT(*)
      INTO V_ERROR_COUNT
      FROM TMP_REQUEST_IMPORT T
     WHERE (
         SELECT COUNT(*)
         FROM MEMBERSHIP M
         WHERE LOWER(BTRIM(M.EMAIL)) = LOWER(BTRIM(T.REQUESTER_EMAIL))
     ) <> 1;
    IF V_ERROR_COUNT > 0 THEN
        RAISE EXCEPTION '% solicitações possuem MEMBERSHIP ausente ou duplicada para o solicitante.', V_ERROR_COUNT;
    END IF;

    SELECT COUNT(*)
      INTO V_ERROR_COUNT
      FROM TMP_REQUEST_IMPORT T
     WHERE (
         SELECT COUNT(*)
         FROM SERVICE_TYPE ST
         JOIN SERVICE_CATEGORY SC
           ON SC.ID = ST.ID_SERVICE_CATEGORY
         WHERE UPPER(BTRIM(SC.NAME)) = UPPER(BTRIM(T.CATEGORY_NAME))
           AND UPPER(BTRIM(ST.NAME)) = UPPER(BTRIM(T.SERVICE_TYPE_NAME))
     ) <> 1;
    IF V_ERROR_COUNT > 0 THEN
        RAISE EXCEPTION '% solicitações possuem SERVICE_TYPE ausente ou duplicado para Categoria + Chamado.', V_ERROR_COUNT;
    END IF;

    SELECT COUNT(*)
      INTO V_ERROR_COUNT
      FROM TMP_REQUEST_IMPORT T
     WHERE T.ID_LOCATION IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM LOCATION L
           WHERE L.ID = T.ID_LOCATION
       );
    IF V_ERROR_COUNT > 0 THEN
        RAISE EXCEPTION '% solicitações referenciam ID_LOCATION inexistente.', V_ERROR_COUNT;
    END IF;
END;
$$;

-- ================================================================
-- REQUEST
-- ================================================================
WITH INSERTED_REQUESTS AS (
    INSERT INTO REQUEST (
        ID,
        ID_REQUEST_TYPE,
        ID_MEMBER_REQUESTER,
        ID_MEMBER_RESPONDER,
        ID_LOCATION,
        ID_SERVICE_TYPE,
        ID_REQUEST_STATUS,
        CREATED_DATE,
        AGREED_DATE,
        STARTED_DATE,
        FINISHED_DATE,
        CANCELED_DATE,
        DESCRIPTION
    )
    SELECT
        T.ID_REQUEST AS ID,
        1 AS ID_REQUEST_TYPE,
        M.ID AS ID_MEMBER_REQUESTER,
        NULL AS ID_MEMBER_RESPONDER,
        T.ID_LOCATION AS ID_LOCATION,
        ST.ID AS ID_SERVICE_TYPE,
        T.ID_REQUEST_STATUS,
        T.CREATED_DATE,
        T.CLOSED_DATE AS AGREED_DATE,
        T.CLOSED_DATE AS STARTED_DATE,
        T.CLOSED_DATE AS FINISHED_DATE,
        T.CANCELED_DATE,
        LEFT(T.DESCRIPTION_FULL, 300) AS DESCRIPTION
    FROM TMP_REQUEST_IMPORT T
    JOIN MEMBERSHIP M
      ON LOWER(BTRIM(M.EMAIL)) = LOWER(BTRIM(T.REQUESTER_EMAIL))
    JOIN SERVICE_CATEGORY SC
      ON UPPER(BTRIM(SC.NAME)) = UPPER(BTRIM(T.CATEGORY_NAME))
    JOIN SERVICE_TYPE ST
      ON ST.ID_SERVICE_CATEGORY = SC.ID
     AND UPPER(BTRIM(ST.NAME)) = UPPER(BTRIM(T.SERVICE_TYPE_NAME))
    RETURNING ID
)
SELECT COUNT(*) AS REQUESTS_INSERTED
FROM INSERTED_REQUESTS;

