-- =========================
-- BUSINESS
-- =========================
INSERT INTO BUSINESS (ID, NAME) VALUES (1, 'TECON Salvador');
INSERT INTO BUSINESS (ID, NAME) VALUES (2, 'Centro Logístico Salvador');

-- =========================
-- REGIONS
-- =========================

INSERT INTO REGIONS (ID, id_business, NAME) VALUES (1, 1, 'Prédio Administrativo');
INSERT INTO REGIONS (ID, id_business, NAME) VALUES (2, 1, 'Almoxarifado');
INSERT INTO REGIONS (ID, id_business, NAME) VALUES (3, 1, 'Armazém');
INSERT INTO REGIONS (ID, id_business, NAME) VALUES (4, 1, 'Manutenção');
INSERT INTO REGIONS (ID, id_business, NAME) VALUES (5, 1, 'Pàtio Operacional');


-- =========================
-- LOCATIONS
-- =========================

INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (5, 1, 'Fila A - Lote 12');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (5, 1, 'Pàtio Operacional');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (5, 1, 'Pàtio Operacional');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (5, 1, 'Pàtio Operacional');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (5, 1, 'Pàtio Operacional');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (1, 1, '2º ANDAR	FINANCEIRO');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (2, 1, '2º ANDAR	COMERCIAL');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (3, 1, '2º ANDAR	SALA ELEVADOR LACERDA');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (4, 1, '2º ANDAR	SALA SOLAR DO UNHÃO');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (5, 1, '2º ANDAR	DIRETORIA OPERACIONAL');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (6, 1, '2º ANDAR	SALA DE REUNIÃO DIRETORIA');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (7, 1, '2º ANDAR	DIRETORIA COMERCIAL');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (8, 1, '2º ANDAR	JURÍDICO');

INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (1, 5, 'POSTO DE COMBUSTÍVEL');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (2, 5, 'ETE');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (3, 5, 'GATE IN');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (4, 5, 'GATE OUT');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (5, 5, 'CAIS');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (6, 5, 'SUBESTAÇÕES ');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (7, 5, 'CANTEIROS');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (8, 5, 'CENTRAIS DE RESÍDUOS');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (9, 5, 'ESTAÇÃO ELEVATÓRIA DE ESGOTO');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (10, 5, 'CASAS DE BOMBAS');
INSERT INTO LOCATIONS (ID, ID_REGION, NAME) VALUES (11, 5, 'TRIAGEM');
 



 




