INSERT INTO TRANSACTION_STATUS (ID, DESCRIPTION) VALUES (1, 'Reprovada');
INSERT INTO TRANSACTION_STATUS (ID, DESCRIPTION) VALUES (2, 'Aprovada');
INSERT INTO TRANSACTION_STATUS (ID, DESCRIPTION) VALUES (3, 'Reparos em móveis');
INSERT INTO TRANSACTION_STATUS (ID, DESCRIPTION) VALUES (4, 'Reparos em móveis');
INSERT INTO TRANSACTION_STATUS (ID, DESCRIPTION) VALUES (5, 'Reparos em móveis');