-- ============================================================
-- OpsHub / SolicitacoesHub
-- Novo diagrama - Script 01: criacao das tabelas
-- Banco alvo: PostgreSQL
-- Observacao: este script cria apenas tabelas, chaves primarias
-- e constraints UNIQUE. As chaves estrangeiras ficam no script 02.
-- ============================================================

BEGIN;

-- ============================================================
-- Tabelas de dominio / apoio
-- ============================================================

CREATE TABLE IF NOT EXISTS sector (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_sector_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS request_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(30) NOT NULL,

    CONSTRAINT uq_request_status_description UNIQUE (description)
);

CREATE TABLE IF NOT EXISTS requests_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_requests_types_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS transaction_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(30) NOT NULL,

    CONSTRAINT uq_transaction_status_description UNIQUE (description)
);

-- ============================================================
-- Estrutura de posicoes / patio
-- ============================================================

CREATE TABLE IF NOT EXISTS business (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,

    CONSTRAINT uq_business_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS regions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_business INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_regions_business_name UNIQUE (id_business, name)
);

CREATE TABLE IF NOT EXISTS locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    location_x DECIMAL(10,8),
    location_y DECIMAL(11,8),

    CONSTRAINT uq_locations_region_name UNIQUE (id_region, name)
);

-- ============================================================
-- Categorias, tipos de servico e campos dinamicos
-- ============================================================

CREATE TABLE IF NOT EXISTS service_category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT uq_service_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS service_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service_category INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),

    CONSTRAINT uq_service_type_category_name UNIQUE (id_service_category, name)
);

CREATE TABLE IF NOT EXISTS service_fields_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service_type INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50),
    options JSONB,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER,

    CONSTRAINT uq_service_fields_types_service_name UNIQUE (id_service_type, name)
);

-- ============================================================
-- Solicitacoes
-- ============================================================

CREATE TABLE IF NOT EXISTS requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request_type INTEGER NOT NULL,
    id_sector_requester INTEGER NOT NULL,
    id_sector_responsible INTEGER,
    id_location INTEGER,
    id_service_type INTEGER NOT NULL,
    id_request_status INTEGER NOT NULL,
    requested_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_datetime TIMESTAMP,
    canceled_datetime TIMESTAMP,
    finished_datetime TIMESTAMP,
    description VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS service_fields_values (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_service_field_types INTEGER NOT NULL,
    id_request INTEGER NOT NULL,
    value JSONB,

    CONSTRAINT uq_service_fields_values_request_field UNIQUE (id_request, id_service_field_types)
);

-- ============================================================
-- Transacoes de solicitacao entre setores
-- Substitui a ideia anterior de request_aprove.
-- ============================================================

CREATE TABLE IF NOT EXISTS request_transaction (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request INTEGER NOT NULL,
    id_sector_proposer INTEGER NOT NULL,
    id_sector_offeree INTEGER NOT NULL,
    id_transaction_status INTEGER NOT NULL,
    proposed_datetime TIMESTAMP,
    description VARCHAR(200)
);

-- ============================================================
-- Tabela de atividades / visitas executadas na solicitacao
-- ============================================================

CREATE TABLE IF NOT EXISTS request_task (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request INTEGER NOT NULL,
    start_datetime TIMESTAMP,
    stop_datetime TIMESTAMP,
    description VARCHAR(100)
);

-- ============================================================
-- Tabela indicada no diagrama como ja existente no ADMSCOL.
-- Mantida aqui como representacao local para ambiente de desenvolvimento.
-- Em producao, caso a tabela real esteja em outro schema, remova este
-- CREATE e ajuste a FK de task_member_occurrence para o schema correto.
-- ============================================================

CREATE TABLE IF NOT EXISTS membership (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idmembership INTEGER,

    CONSTRAINT uq_membership_idmembership UNIQUE (idmembership)
);

-- ============================================================
-- Associativa para vincular executantes as ocorrencias/tarefas
-- ============================================================

CREATE TABLE IF NOT EXISTS task_member_occurrence (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_task INTEGER NOT NULL,
    id_membership INTEGER NOT NULL,

    CONSTRAINT uq_task_member_occurrence UNIQUE (id_task, id_membership)
);

COMMIT;
-- ============================================================
-- OpsHub / SolicitacoesHub
-- Novo diagrama - Script 02: criacao das chaves estrangeiras
-- e indices de apoio
-- Banco alvo: PostgreSQL
-- Execute apos o script 01_CREATE_TABLES_NEW_DIAGRAM.sql
-- ============================================================

BEGIN;

-- ============================================================
-- Foreign keys: posicoes / patio
-- ============================================================

ALTER TABLE regions
    ADD CONSTRAINT fk_regions_business
    FOREIGN KEY (id_business)
    REFERENCES business (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE locations
    ADD CONSTRAINT fk_locations_regions
    FOREIGN KEY (id_region)
    REFERENCES regions (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

-- ============================================================
-- Foreign keys: tipos de servico e campos dinamicos
-- ============================================================

ALTER TABLE service_type
    ADD CONSTRAINT fk_service_type_service_category
    FOREIGN KEY (id_service_category)
    REFERENCES service_category (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE service_fields_types
    ADD CONSTRAINT fk_service_fields_types_service_type
    FOREIGN KEY (id_service_type)
    REFERENCES service_type (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

-- ============================================================
-- Foreign keys: solicitacoes
-- ============================================================

ALTER TABLE requests
    ADD CONSTRAINT fk_requests_requests_types
    FOREIGN KEY (id_request_type)
    REFERENCES requests_types (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE requests
    ADD CONSTRAINT fk_requests_sector_requester
    FOREIGN KEY (id_sector_requester)
    REFERENCES sector (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE requests
    ADD CONSTRAINT fk_requests_sector_responsible
    FOREIGN KEY (id_sector_responsible)
    REFERENCES sector (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE requests
    ADD CONSTRAINT fk_requests_locations
    FOREIGN KEY (id_location)
    REFERENCES locations (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE requests
    ADD CONSTRAINT fk_requests_service_type
    FOREIGN KEY (id_service_type)
    REFERENCES service_type (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE requests
    ADD CONSTRAINT fk_requests_request_status
    FOREIGN KEY (id_request_status)
    REFERENCES request_status (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE service_fields_values
    ADD CONSTRAINT fk_service_fields_values_field_type
    FOREIGN KEY (id_service_field_types)
    REFERENCES service_fields_types (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE service_fields_values
    ADD CONSTRAINT fk_service_fields_values_request
    FOREIGN KEY (id_request)
    REFERENCES requests (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;

-- ============================================================
-- Foreign keys: transacoes de solicitacao entre setores
-- ============================================================

ALTER TABLE request_transaction
    ADD CONSTRAINT fk_request_transaction_request
    FOREIGN KEY (id_request)
    REFERENCES requests (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE request_transaction
    ADD CONSTRAINT fk_request_transaction_sector_proposer
    FOREIGN KEY (id_sector_proposer)
    REFERENCES sector (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE request_transaction
    ADD CONSTRAINT fk_request_transaction_sector_offeree
    FOREIGN KEY (id_sector_offeree)
    REFERENCES sector (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE request_transaction
    ADD CONSTRAINT fk_request_transaction_status
    FOREIGN KEY (id_transaction_status)
    REFERENCES transaction_status (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

-- ============================================================
-- Foreign keys: tarefas / visitas e executantes
-- ============================================================

ALTER TABLE request_task
    ADD CONSTRAINT fk_request_task_request
    FOREIGN KEY (id_request)
    REFERENCES requests (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE task_member_occurrence
    ADD CONSTRAINT fk_task_member_occurrence_task
    FOREIGN KEY (id_task)
    REFERENCES request_task (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE task_member_occurrence
    ADD CONSTRAINT fk_task_member_occurrence_membership
    FOREIGN KEY (id_membership)
    REFERENCES membership (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

-- ============================================================
-- Indices para FKs e consultas frequentes
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_regions_id_business
    ON regions (id_business);

CREATE INDEX IF NOT EXISTS idx_locations_id_region
    ON locations (id_region);

CREATE INDEX IF NOT EXISTS idx_service_type_id_service_category
    ON service_type (id_service_category);

CREATE INDEX IF NOT EXISTS idx_service_fields_types_id_service_type
    ON service_fields_types (id_service_type);

CREATE INDEX IF NOT EXISTS idx_requests_id_request_type
    ON requests (id_request_type);

CREATE INDEX IF NOT EXISTS idx_requests_id_sector_requester
    ON requests (id_sector_requester);

CREATE INDEX IF NOT EXISTS idx_requests_id_sector_responsible
    ON requests (id_sector_responsible);

CREATE INDEX IF NOT EXISTS idx_requests_id_location
    ON requests (id_location);

CREATE INDEX IF NOT EXISTS idx_requests_id_service_type
    ON requests (id_service_type);

CREATE INDEX IF NOT EXISTS idx_requests_id_request_status
    ON requests (id_request_status);

CREATE INDEX IF NOT EXISTS idx_requests_requested_datetime
    ON requests (requested_datetime);

CREATE INDEX IF NOT EXISTS idx_requests_approved_datetime
    ON requests (approved_datetime);

CREATE INDEX IF NOT EXISTS idx_requests_finished_datetime
    ON requests (finished_datetime);

CREATE INDEX IF NOT EXISTS idx_service_fields_values_id_field_type
    ON service_fields_values (id_service_field_types);

CREATE INDEX IF NOT EXISTS idx_service_fields_values_id_request
    ON service_fields_values (id_request);

CREATE INDEX IF NOT EXISTS idx_request_transaction_id_request
    ON request_transaction (id_request);

CREATE INDEX IF NOT EXISTS idx_request_transaction_id_sector_proposer
    ON request_transaction (id_sector_proposer);

CREATE INDEX IF NOT EXISTS idx_request_transaction_id_sector_offeree
    ON request_transaction (id_sector_offeree);

CREATE INDEX IF NOT EXISTS idx_request_transaction_id_transaction_status
    ON request_transaction (id_transaction_status);

CREATE INDEX IF NOT EXISTS idx_request_transaction_proposed_datetime
    ON request_transaction (proposed_datetime);

CREATE INDEX IF NOT EXISTS idx_request_task_id_request
    ON request_task (id_request);

CREATE INDEX IF NOT EXISTS idx_task_member_occurrence_id_task
    ON task_member_occurrence (id_task);

CREATE INDEX IF NOT EXISTS idx_task_member_occurrence_id_membership
    ON task_member_occurrence (id_membership);

COMMIT;
