-- PostgreSQL: executar uma unica vez em uma base existente completa.
-- Configure search_path para o schema da aplicacao antes de executar.
-- Pare a API durante a renomeacao e publique o backend com o prefixo OHFC_.
-- Nao executar em bases novas criadas pelos scripts ja prefixados.
-- Colunas, constraints e sequencias existentes mantem seus nomes.

BEGIN;

ALTER TABLE BUSINESS RENAME TO OHFC_BUSINESS;
ALTER TABLE CHECKLIST_FIELD_TYPE RENAME TO OHFC_CHECKLIST_FIELD_TYPE;
ALTER TABLE CHECKLIST_FIELD_VALUE RENAME TO OHFC_CHECKLIST_FIELD_VALUE;
ALTER TABLE CHECKLIST_TYPE RENAME TO OHFC_CHECKLIST_TYPE;
ALTER TABLE LOCATION RENAME TO OHFC_LOCATION;
ALTER TABLE MEMBERSHIP RENAME TO OHFC_MEMBERSHIP;
ALTER TABLE REGION RENAME TO OHFC_REGION;
ALTER TABLE REQUEST RENAME TO OHFC_REQUEST;
ALTER TABLE REQUEST_STATUS RENAME TO OHFC_REQUEST_STATUS;
ALTER TABLE REQUEST_TASK RENAME TO OHFC_REQUEST_TASK;
ALTER TABLE REQUEST_TASK_CHECKLIST RENAME TO OHFC_REQUEST_TASK_CHECKLIST;
ALTER TABLE REQUEST_TASK_MEDIA RENAME TO OHFC_REQUEST_TASK_MEDIA;
ALTER TABLE REQUEST_TRANSACTION RENAME TO OHFC_REQUEST_TRANSACTION;
ALTER TABLE REQUEST_TRANSACTION_STATUS RENAME TO OHFC_REQUEST_TRANSACTION_STATUS;
ALTER TABLE REQUEST_TYPE RENAME TO OHFC_REQUEST_TYPE;
ALTER TABLE SECTOR RENAME TO OHFC_SECTOR;
ALTER TABLE SERVICE_CATEGORY RENAME TO OHFC_SERVICE_CATEGORY;
ALTER TABLE SERVICE_FIELD_MEDIA RENAME TO OHFC_SERVICE_FIELD_MEDIA;
ALTER TABLE SERVICE_FIELD_TYPE RENAME TO OHFC_SERVICE_FIELD_TYPE;
ALTER TABLE SERVICE_FIELD_VALUE RENAME TO OHFC_SERVICE_FIELD_VALUE;
ALTER TABLE SERVICE_TYPE RENAME TO OHFC_SERVICE_TYPE;
ALTER TABLE SLA RENAME TO OHFC_SLA;
ALTER TABLE TASK_MEMBER_OCCURRENCE RENAME TO OHFC_TASK_MEMBER_OCCURRENCE;

COMMIT;
