-- ================================================================
-- SERVICE_CATEGORY
-- ================================================================
INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'ARTÍFICE'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'ARTÍFICE'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'CLIMATIZAÇÃO E REFRIGERAÇÃO'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'COPA'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'COPA'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'INSTALAÇÕES ELÉTRICAS'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'INSTALAÇÕES ELÉTRICAS'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'INSTALAÇÕES HIDRÁULICAS'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'INSTALAÇÕES HIDRÁULICAS'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'JARDINAGEM'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'JARDINAGEM'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'MANUTENÇÂO CIVIL'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'MANUTENÇÂO CIVIL'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'NOVOS PROJETOS'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'NOVOS PROJETOS'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA'
);

INSERT INTO SERVICE_CATEGORY (NAME)
SELECT 'PMOC'
WHERE NOT EXISTS (
    SELECT 1 FROM SERVICE_CATEGORY
    WHERE NAME = 'PMOC'
);

COMMIT;
