-- ================================================================
-- SERVICE_FIELD_TYPE
-- ================================================================
-- ARTÍFICE > Fixação de Placas/Quadros
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (1, 1, 'Referência', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- ARTÍFICE > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (2, 2, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- ARTÍFICE > Regulagem de porta
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (3, 3, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (4, 3, 'Problema identificado', 'MULTI_SELECT', '["Não fecha", "Desalinhada", "outro", "Não abre bem"]'::JSONB,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (5, 3, 'Tipo da porta', 'SINGLE_SELECT', '["Madeira", "Corta-fogo", "Vidro", "Metálica"]'::JSONB,
       TRUE, TRUE, 3);

-- ARTÍFICE > Reparos em móveis
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (6, 4, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- ARTÍFICE > Substituição de dispenser (papel higiênico, papel toalha ou sabão)
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (7, 5, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (8, 5, 'Tipo do dispenser', 'SINGLE_SELECT', '["Papel higiênico", "Sabão", "Papel toalha"]'::JSONB,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (9, 5, 'Motivo', 'SINGLE_SELECT', '["Outro", "Quebrado", "Não fixa na parede"]'::JSONB,
       TRUE, TRUE, 3);

-- ARTÍFICE > Substituição de fitas de demarcação lisa/antiderrapante
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (10, 6, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (11, 6, 'Observações', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- ARTÍFICE > Substituição de tampa de vaso sanitário
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (12, 7, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (13, 7, 'Observações', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- ARTÍFICE > Troca de fechadura/miolo
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (14, 8, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (15, 8, 'Observações', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (16, 8, 'Motivo da troca', 'SINGLE_SELECT', '["Outro", "Danificada", "Chave perdida"]'::JSONB,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (17, 8, 'Observações da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 4);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento com avaria evidente
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (18, 9, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (19, 9, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento não liga
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (20, 10, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (21, 10, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento não refrigera/climatiza
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (22, 11, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (23, 11, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Instalação de equipamento
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (24, 12, 'Foto', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (25, 12, 'Técnico responsável', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (26, 13, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Remanejamento de unidade evaporadora/condensadora
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (27, 14, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (28, 14, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Vazamento de água em equipamento
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (29, 15, 'Quase sempre visível (exemplo ar-57)', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (30, 15, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- COPA > Limpeza de geladeira ou micro-ondas
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (31, 16, 'Equipamento que necessita limpeza', 'MULTI_SELECT', '["Microondas", "Geladeira"]'::JSONB,
       TRUE, TRUE, 1);

-- Dúvida Aplicativo > Dificuldade com a reserva
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (32, 17, 'Está tendo dificuldade em fazer a reserva?', 'BOOL', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (33, 17, 'Descreva a situação?', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (34, 17, 'Caso esteja aparecendo algum erro, envie o print da tela', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (35, 17, 'Está conforme?', 'TEXT', NULL,
       TRUE, TRUE, 4);

-- INSTALAÇÕES ELÉTRICAS > Interruptor ou Tomada com defeito/quebrado
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (36, 18, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (37, 18, 'Tet', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- INSTALAÇÕES ELÉTRICAS > Lâmpadas queimadas
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (38, 19, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (39, 19, 'Qual o seu problema?', 'SINGLE_SELECT', '["Lâmpada/refletor queimada", "Problema no interruptor"]'::JSONB,
       TRUE, TRUE, 2);

-- INSTALAÇÕES ELÉTRICAS > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (40, 21, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- INSTALAÇÕES ELÉTRICAS > Quadro elétrico desarmando
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 22, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- INSTALAÇÕES ELÉTRICAS > Regularização de extensões/plugs/equipamentos
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (42, 23, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (43, 23, 'Tipo de item', 'SINGLE_SELECT', '["Equipamento elétrico", "Plug"]'::JSONB,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 23, 'Quantidade de itens', 'NUMBER', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 23, 'Risco identificado', 'TEXT', NULL,
       TRUE, TRUE, 4);

-- INSTALAÇÕES ELÉTRICAS > Substituição de biruta
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (46, 25, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 25, 'Quantidade', 'NUMBER', NULL,
       TRUE, TRUE, 2);

-- INSTALAÇÕES ELÉTRICAS > Tomada com defeito/quebrada
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (48, 26, 'Motivo', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 26, 'Quantidade', 'NUMBER', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 26, 'Tipo de tomada', 'TEXT', NULL,
       TRUE, TRUE, 3);

-- INSTALAÇÕES HIDRÁULICAS > Ambiente sem água
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 27, 'Tipo de ponto afetado', 'SINGLE_SELECT', '["OUTRO", "VASO SANITARIO"]'::JSONB,
       TRUE, TRUE, 1);

-- INSTALAÇÕES HIDRÁULICAS > Entupimento de pia, mictório ou vaso
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (52, 28, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (53, 28, 'Ponto afetado', 'SINGLE_SELECT', '["Mictório", "Outro", "Vaso sanitário"]'::JSONB,
       TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Higienização dos bebedouros
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (54, 29, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (55, 29, 'Quantidade de bebedouro', 'NUMBER', NULL,
       TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Obstrução de caixa de esgoto
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (56, 30, 'Obstrução identificada', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (57, 30, 'Quantidade de caixas', 'NUMBER', NULL,
       TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (58, 31, 'Foto da necessidade', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- INSTALAÇÕES HIDRÁULICAS > Registro com defeito
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (59, 32, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (60, 32, 'Problema identificado', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Vazamento em tubulação
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (61, 33, 'Itensidade', 'SINGLE_SELECT', '["FLUXO CONTÍNUO", "GOTEJAMENTO"]'::JSONB,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (62, 33, 'Foto', 'TEXT', NULL,
       TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Vazamento em válvula de descarga
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (63, 34, 'Frequencia do vazamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- JARDINAGEM > Poda de árvore ou arbusto
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (64, 35, 'Insira imagem', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- JARDINAGEM > Retirada de vegetação (ervas daninhas)
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (65, 36, 'Área aproximada afetada (metros quadrados)', 'NUMBER', NULL,
       TRUE, TRUE, 1);

-- MANUTENÇÂO CIVIL > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (66, 38, 'Foto/anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- MANUTENÇÂO CIVIL > Reparo de pisos e revestimentos
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (67, 39, 'Anexo da ocorrência', 'TEXT', NULL,
       TRUE, TRUE, 1);

-- NOVOS PROJETOS > Novo Projeto ou Readequação de Área
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (68, 40, 'Setor demandante', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (69, 40, 'Projeto ou readequação de área', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (70, 40, 'Número da pt e/ou apr', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (71, 40, 'Registros', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (72, 40, 'Tempo', 'TEXT', NULL,
       TRUE, TRUE, 5);

-- NOVOS PROJETOS > Solicitação de Recursos Diversos
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (73, 41, 'O que será realizado?', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (74, 41, 'Onde será realizado?', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (75, 41, 'Há necessidade de artificies ?', 'BOOL', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (76, 41, 'qual o nível urgência?', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (77, 41, 'Envolve instalações/modificações elétricas ?', 'BOOL', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (78, 41, 'Envolve instalações/modificações hidráulicas ?', 'BOOL', NULL,
       TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (79, 41, 'Envolve instalações/modificações de refirgeração ?', 'BOOL', NULL,
       TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (80, 41, 'Há necessidade de materiais de pintura ?', 'BOOL', NULL,
       TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (81, 41, 'Se houver documentos do projeto anexar', 'TEXT', NULL,
       TRUE, TRUE, 9);

-- PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA > Pintura de segurança/operacional/predial/metálica
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (82, 42, 'Observações', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (83, 42, 'Pintura', 'SINGLE_SELECT', '["Outros", "Faixa de pedestre"]'::JSONB,
       TRUE, TRUE, 2);

-- PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA > TESTE Pintura
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (84, 43, 'Possui pt vinculada', 'BOOL', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (85, 43, 'Tipo de pintura', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (86, 43, 'Data de finalização', 'DATE', NULL,
       TRUE, TRUE, 3);

-- PMOC > PMOC ANUAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (87, 44, 'Tag do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (88, 44, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (89, 44, 'Verificar a operação de drenagem de água da bandeja e realizar limpeza do dreno', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (90, 44, 'Lavar o gabinete, as bandejas e as serpentinas, sem o uso de produtos desengraxantes e corrosivos', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (91, 44, 'Limpar os ventiladores (carcaça e rotor)', 'TEXT', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (92, 44, 'Filtro verificar e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas; ', 'TEXT', NULL,
       TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (93, 44, 'Verificar presença de ruídos e/ou vibrações anormais', 'TEXT', NULL,
       TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (94, 44, 'Verificar a vedação dos painéis de fechamento do gabinete', 'TEXT', NULL,
       TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (95, 44, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL,
       TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (96, 44, 'Verificar o estado de conservação do isolamento térmico', 'TEXT', NULL,
       TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (97, 44, 'Verificação de existência de vazamentos', 'TEXT', NULL,
       TRUE, TRUE, 11);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (98, 44, 'Hidrojateamento geral do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 12);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (99, 44, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB,
       TRUE, TRUE, 13);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (100, 44, 'Leituras de tensão', 'TEXT', NULL,
       TRUE, TRUE, 14);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (101, 44, 'Leitura de corrente', 'TEXT', NULL,
       TRUE, TRUE, 15);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (102, 44, 'Leitura de pressão', 'TEXT', NULL,
       TRUE, TRUE, 16);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (103, 44, 'Verificação de terminais', 'TEXT', NULL,
       TRUE, TRUE, 17);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (104, 44, 'Verificação de fiação e contatos', 'TEXT', NULL,
       TRUE, TRUE, 18);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (105, 44, 'Reaperto de conexões', 'TEXT', NULL,
       TRUE, TRUE, 19);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (106, 44, 'Medição de diferencial', 'TEXT', NULL,
       TRUE, TRUE, 20);

-- PMOC > PMOC BIMESTRAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (107, 45, 'Tag do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (108, 45, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (109, 45, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (110, 45, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (111, 45, 'Medição de diferencial', 'TEXT', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (112, 45, 'Verificação da operação de drenagem de água da bandeja e limpeza do dreno', 'TEXT', NULL,
       TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (113, 45, 'Lavagem do gabinete, das bandejas e das serpentinas, sem o uso de produtos desengraxantes e corrosiv', 'TEXT', NULL,
       TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (114, 45, 'Limpeza dos ventiladores (carcaça e rotor)', 'TEXT', NULL,
       TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (115, 45, 'Filtro verificação e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas', 'TEXT', NULL,
       TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (116, 45, 'Verificação da presença de ruídos e/ou vibrações anormais', 'TEXT', NULL,
       TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (117, 45, 'Verificação da vedação dos painéis de fechamento do gabinete', 'TEXT', NULL,
       TRUE, TRUE, 11);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (118, 45, 'Verificação do estado de conservação do isolamento térmico', 'TEXT', NULL,
       TRUE, TRUE, 12);

-- PMOC > PMOC BIMESTRAL Cortina de ar
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (119, 46, 'Tag do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (120, 46, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (121, 46, 'Verificação e limpeza da carenagem', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (122, 46, 'Verificação e limpeza da turbina', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (123, 46, 'Verificação e limpeza dos defletores', 'TEXT', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (124, 46, 'Verificação e limpeza do direcionamento de ar', 'TEXT', NULL,
       TRUE, TRUE, 6);

-- PMOC > PMOC MENSAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (125, 47, 'Tag do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (126, 47, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (127, 47, 'Verificar a operação de drenagem de água da bandeja e realizar limpeza do dreno', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (128, 47, 'Lavar o gabinete, as bandejas e as serpentinas, sem o uso de produtos desengraxantes e corrosivos', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (129, 47, 'Limpar os ventiladores (carcaça e rotor)', 'TEXT', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (130, 47, 'Filtro verificar e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas; ', 'TEXT', NULL,
       TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (131, 47, 'Verificar presença de ruídos e/ou vibrações anormais', 'TEXT', NULL,
       TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (132, 47, 'Verificar a vedação dos painéis de fechamento do gabinete', 'TEXT', NULL,
       TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (133, 47, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL,
       TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (134, 47, 'Verificar o estado de conservação do isolamento térmico', 'TEXT', NULL,
       TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (135, 47, 'Medição do diferencial', 'TEXT', NULL,
       TRUE, TRUE, 11);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (136, 47, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB,
       TRUE, TRUE, 12);

-- PMOC > PMOC MENSAL Cortina de ar
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (137, 48, 'Tag do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (138, 48, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (139, 48, 'Verificação e limpeza da carenagem', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (140, 48, 'Verificação e limpeza da turbina', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (141, 48, 'Verificação e limpeza dos defletores', 'TEXT', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (142, 48, 'Verificação e limpeza do direcionamento de ar', 'TEXT', NULL,
       TRUE, TRUE, 6);

-- PMOC > PMOC SEMESTRAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (143, 49, 'Tag do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (144, 49, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (145, 49, 'Verificar a operação de drenagem de água da bandeja e realizar limpeza do dreno', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (146, 49, 'Lavar o gabinete, as bandejas e as serpentinas, sem o uso de produtos desengraxantes e corrosivos', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (147, 49, 'Limpar os ventiladores (carcaça e rotor)', 'TEXT', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (148, 49, 'Filtro verificar e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas; ', 'TEXT', NULL,
       TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (149, 49, 'Verificar presença de ruídos e/ou vibrações anormais', 'TEXT', NULL,
       TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (150, 49, 'Verificar a vedação dos painéis de fechamento do gabinete', 'TEXT', NULL,
       TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (151, 49, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL,
       TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (152, 49, 'Verificar o estado de conservação do isolamento térmico', 'TEXT', NULL,
       TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (153, 49, 'Verificação de existência de vazamentos', 'TEXT', NULL,
       TRUE, TRUE, 11);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (154, 49, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB,
       TRUE, TRUE, 12);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (155, 49, 'Leituras de tensão', 'TEXT', NULL,
       TRUE, TRUE, 13);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (156, 49, 'Leitura de corrente', 'TEXT', NULL,
       TRUE, TRUE, 14);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (157, 49, 'Leitura de pressão', 'TEXT', NULL,
       TRUE, TRUE, 15);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (158, 49, 'Verificação de terminais', 'TEXT', NULL,
       TRUE, TRUE, 16);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (159, 49, 'Verificação de fiação e contatos', 'TEXT', NULL,
       TRUE, TRUE, 17);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (160, 49, 'Reaperto de conexões', 'TEXT', NULL,
       TRUE, TRUE, 18);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (161, 49, 'Medição de diferencial', 'TEXT', NULL,
       TRUE, TRUE, 19);

-- PMOC > PMOC SEMESTRAL Cortina de ar
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (162, 50, 'Tag do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (163, 50, 'Limpeza dos componentes elétricos', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (164, 50, 'Verificar conexões eletricas', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (165, 50, 'Lubrificação do eixo e do sistema de fixação da turbina', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (166, 50, 'Limpeza de carenagem', 'TEXT', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (167, 50, 'Limpeza de turbina', 'TEXT', NULL,
       TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (168, 50, 'Limpeza do direcionamento de ar', 'TEXT', NULL,
       TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (169, 50, 'Medição de corrente', 'TEXT', NULL,
       TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (170, 50, 'Medição de tensão', 'TEXT', NULL,
       TRUE, TRUE, 9);

-- PMOC > PMOC TRIMESTRAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (171, 51, 'Tag do equipamento', 'TEXT', NULL,
       TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (172, 51, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL,
       TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (173, 51, 'Verificar a operação de drenagem de água da bandeja e realizar limpeza do dreno', 'TEXT', NULL,
       TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (174, 51, 'Lavar o gabinete, as bandejas e as serpentinas, sem o uso de produtos desengraxantes e corrosivos', 'TEXT', NULL,
       TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (175, 51, 'Limpar os ventiladores (carcaça e rotor)', 'TEXT', NULL,
       TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (176, 51, 'Filtro verificar e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas; ', 'TEXT', NULL,
       TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (177, 51, 'Verificar presença de ruídos e/ou vibrações anormais', 'TEXT', NULL,
       TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (178, 51, 'Verificar a vedação dos painéis de fechamento do gabinete', 'TEXT', NULL,
       TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (179, 51, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL,
       TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (180, 51, 'Verificar o estado de conservação do isolamento térmico', 'TEXT', NULL,
       TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID, ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (181, 51, 'Medição de diferencial', 'TEXT', NULL,
       TRUE, TRUE, 11);

COMMIT;
