-- ================================================================
-- SERVICE_FIELD_TYPE
-- ================================================================
-- ARTÍFICE > Fixação de Placas/Quadros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (1, 'Referência', 'TEXT', NULL, TRUE, TRUE, 1);

-- ARTÍFICE > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (2, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 1);

-- ARTÍFICE > Regulagem de porta
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (3, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (3, 'Problema identificado', 'MULTI_SELECT', '["Não fecha", "Desalinhada", "outro", "Não abre bem"]'::JSONB, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (3, 'Tipo da porta', 'SINGLE_SELECT', '["Madeira", "Corta-fogo", "Vidro", "Metálica"]'::JSONB, TRUE, TRUE, 3);

-- ARTÍFICE > Reparos em móveis
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (4, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

-- ARTÍFICE > Substituição de dispenser (papel higiênico, papel toalha ou sabão)
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (5, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (5, 'Tipo do dispenser', 'SINGLE_SELECT', '["Papel higiênico", "Sabão", "Papel toalha"]'::JSONB, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (5, 'Motivo', 'SINGLE_SELECT', '["Outro", "Quebrado", "Não fixa na parede"]'::JSONB, TRUE, TRUE, 3);

-- ARTÍFICE > Substituição de fitas de demarcação lisa/antiderrapante
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (6, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (6, 'Observações', 'TEXT', NULL, TRUE, TRUE, 2);

-- ARTÍFICE > Substituição de tampa de vaso sanitário
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (7, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (7, 'Observações', 'TEXT', NULL, TRUE, TRUE, 2);

-- ARTÍFICE > Troca de fechadura/miolo
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (8, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (8, 'Observações', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (8, 'Motivo da troca', 'SINGLE_SELECT', '["Outro", "Danificada", "Chave perdida"]'::JSONB, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (8, 'Observações da ocorrência', 'TEXT', NULL, TRUE, TRUE, 4);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento com avaria evidente
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (9, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (9, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL, TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento não liga
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (10, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (10, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL, TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Equipamento não refrigera/climatiza
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (11, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (11, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL, TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Instalação de equipamento
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (12, 'Foto', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (12, 'Técnico responsável', 'TEXT', NULL, TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (13, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 1);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Remanejamento de unidade evaporadora/condensadora
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (14, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (14, 'Quase sempre visíveis (exemplo ar-57)', 'TEXT', NULL, TRUE, TRUE, 2);

-- CLIMATIZAÇÃO E REFRIGERAÇÃO > Vazamento de água em equipamento
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (15, 'Quase sempre visível (exemplo ar-57)', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (15, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 2);

-- COPA > Limpeza de geladeira ou micro-ondas
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (16, 'Equipamento que necessita limpeza', 'MULTI_SELECT', '["Microondas", "Geladeira"]'::JSONB, TRUE, TRUE, 1);

-- Dúvida Aplicativo > Dificuldade com a reserva
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (17, 'Está tendo dificuldade em fazer a reserva?', 'BOOL', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (17, 'Descreva a situação?', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (17, 'Caso esteja aparecendo algum erro, envie o print da tela', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (17, 'Está conforme?', 'TEXT', NULL, TRUE, TRUE, 4);

-- INSTALAÇÕES ELÉTRICAS > Interruptor ou Tomada com defeito/quebrado
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (18, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (18, 'Tet', 'TEXT', NULL, TRUE, TRUE, 2);

-- INSTALAÇÕES ELÉTRICAS > Lâmpadas queimadas
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (19, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (19, 'Qual o seu problema?', 'SINGLE_SELECT', '["Lâmpada/refletor queimada", "Problema no interruptor"]'::JSONB, TRUE, TRUE, 2);

-- INSTALAÇÕES ELÉTRICAS > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (21, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 1);

-- INSTALAÇÕES ELÉTRICAS > Quadro elétrico desarmando
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (22, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

-- INSTALAÇÕES ELÉTRICAS > Regularização de extensões/plugs/equipamentos
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (23, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (23, 'Tipo de item', 'SINGLE_SELECT', '["Equipamento elétrico", "Plug"]'::JSONB, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (23, 'Quantidade de itens', 'NUMBER', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (23, 'Risco identificado', 'TEXT', NULL, TRUE, TRUE, 4);

-- INSTALAÇÕES ELÉTRICAS > Substituição de biruta
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (25, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (25, 'Quantidade', 'NUMBER', NULL, TRUE, TRUE, 2);

-- INSTALAÇÕES ELÉTRICAS > Tomada com defeito/quebrada
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (26, 'Motivo', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (26, 'Quantidade', 'NUMBER', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (26, 'Tipo de tomada', 'TEXT', NULL, TRUE, TRUE, 3);

-- INSTALAÇÕES HIDRÁULICAS > Ambiente sem água
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (27, 'Tipo de ponto afetado', 'SINGLE_SELECT', '["OUTRO", "VASO SANITARIO"]'::JSONB, TRUE, TRUE, 1);

-- INSTALAÇÕES HIDRÁULICAS > Entupimento de pia, mictório ou vaso
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (28, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (28, 'Ponto afetado', 'SINGLE_SELECT', '["Mictório", "Outro", "Vaso sanitário"]'::JSONB, TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Higienização dos bebedouros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (29, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (29, 'Quantidade de bebedouro', 'NUMBER', NULL, TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Obstrução de caixa de esgoto
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (30, 'Obstrução identificada', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (30, 'Quantidade de caixas', 'NUMBER', NULL, TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (31, 'Foto da necessidade', 'TEXT', NULL, TRUE, TRUE, 1);

-- INSTALAÇÕES HIDRÁULICAS > Registro com defeito
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (32, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (32, 'Problema identificado', 'TEXT', NULL, TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Vazamento em tubulação
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (33, 'Itensidade', 'SINGLE_SELECT', '["FLUXO CONTÍNUO", "GOTEJAMENTO"]'::JSONB, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (33, 'Foto', 'TEXT', NULL, TRUE, TRUE, 2);

-- INSTALAÇÕES HIDRÁULICAS > Vazamento em válvula de descarga
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (34, 'Frequencia do vazamento', 'TEXT', NULL, TRUE, TRUE, 1);

-- JARDINAGEM > Poda de árvore ou arbusto
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (35, 'Insira imagem', 'TEXT', NULL, TRUE, TRUE, 1);

-- JARDINAGEM > Retirada de vegetação (ervas daninhas)
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (36, 'Área aproximada afetada (metros quadrados)', 'NUMBER', NULL, TRUE, TRUE, 1);

-- MANUTENÇÂO CIVIL > Outros
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (38, 'Foto/anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

-- MANUTENÇÂO CIVIL > Reparo de pisos e revestimentos
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (39, 'Anexo da ocorrência', 'TEXT', NULL, TRUE, TRUE, 1);

-- NOVOS PROJETOS > Novo Projeto ou Readequação de Área
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (40, 'Setor demandante', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (40, 'Projeto ou readequação de área', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (40, 'Número da pt e/ou apr', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (40, 'Registros', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (40, 'Tempo', 'TEXT', NULL, TRUE, TRUE, 5);

-- NOVOS PROJETOS > Solicitação de Recursos Diversos
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'O que será realizado?', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'Onde será realizado?', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'Há necessidade de artificies ?', 'BOOL', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'qual o nível urgência?', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'Envolve instalações/modificações elétricas ?', 'BOOL', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'Envolve instalações/modificações hidráulicas ?', 'BOOL', NULL, TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'Envolve instalações/modificações de refirgeração ?', 'BOOL', NULL, TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'Há necessidade de materiais de pintura ?', 'BOOL', NULL, TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (41, 'Se houver documentos do projeto anexar', 'TEXT', NULL, TRUE, TRUE, 9);

-- PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA > Pintura de segurança/operacional/predial/metálica
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (42, 'Observações', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (42, 'Pintura', 'SINGLE_SELECT', '["Outros", "Faixa de pedestre"]'::JSONB, TRUE, TRUE, 2);

-- PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA > TESTE Pintura
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (43, 'Possui pt vinculada', 'BOOL', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (43, 'Tipo de pintura', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (43, 'Data de finalização', 'DATE', NULL, TRUE, TRUE, 3);

-- PMOC > PMOC ANUAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Tag do equipamento', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificar a operação de drenagem de água da bandeja e realizar limpeza do dreno', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Lavar o gabinete, as bandejas e as serpentinas, sem o uso de produtos desengraxantes e corrosivos', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Limpar os ventiladores (carcaça e rotor)', 'TEXT', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Filtro verificar e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas; ', 'TEXT', NULL, TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificar presença de ruídos e/ou vibrações anormais', 'TEXT', NULL, TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificar a vedação dos painéis de fechamento do gabinete', 'TEXT', NULL, TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL, TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificar o estado de conservação do isolamento térmico', 'TEXT', NULL, TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificação de existência de vazamentos', 'TEXT', NULL, TRUE, TRUE, 11);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Hidrojateamento geral do equipamento', 'TEXT', NULL, TRUE, TRUE, 12);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB, TRUE, TRUE, 13);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Leituras de tensão', 'TEXT', NULL, TRUE, TRUE, 14);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Leitura de corrente', 'TEXT', NULL, TRUE, TRUE, 15);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Leitura de pressão', 'TEXT', NULL, TRUE, TRUE, 16);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificação de terminais', 'TEXT', NULL, TRUE, TRUE, 17);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Verificação de fiação e contatos', 'TEXT', NULL, TRUE, TRUE, 18);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Reaperto de conexões', 'TEXT', NULL, TRUE, TRUE, 19);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (44, 'Medição de diferencial', 'TEXT', NULL, TRUE, TRUE, 20);

-- PMOC > PMOC BIMESTRAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Tag do equipamento', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Medição de diferencial', 'TEXT', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Verificação da operação de drenagem de água da bandeja e limpeza do dreno', 'TEXT', NULL, TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Lavagem do gabinete, das bandejas e das serpentinas, sem o uso de produtos desengraxantes e corrosiv', 'TEXT', NULL, TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Limpeza dos ventiladores (carcaça e rotor)', 'TEXT', NULL, TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Filtro verificação e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas', 'TEXT', NULL, TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Verificação da presença de ruídos e/ou vibrações anormais', 'TEXT', NULL, TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Verificação da vedação dos painéis de fechamento do gabinete', 'TEXT', NULL, TRUE, TRUE, 11);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (45, 'Verificação do estado de conservação do isolamento térmico', 'TEXT', NULL, TRUE, TRUE, 12);

-- PMOC > PMOC BIMESTRAL Cortina de ar
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (46, 'Tag do equipamento', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (46, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (46, 'Verificação e limpeza da carenagem', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (46, 'Verificação e limpeza da turbina', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (46, 'Verificação e limpeza dos defletores', 'TEXT', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (46, 'Verificação e limpeza do direcionamento de ar', 'TEXT', NULL, TRUE, TRUE, 6);

-- PMOC > PMOC MENSAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Tag do equipamento', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Verificar a operação de drenagem de água da bandeja e realizar limpeza do dreno', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Lavar o gabinete, as bandejas e as serpentinas, sem o uso de produtos desengraxantes e corrosivos', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Limpar os ventiladores (carcaça e rotor)', 'TEXT', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Filtro verificar e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas; ', 'TEXT', NULL, TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Verificar presença de ruídos e/ou vibrações anormais', 'TEXT', NULL, TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Verificar a vedação dos painéis de fechamento do gabinete', 'TEXT', NULL, TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL, TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Verificar o estado de conservação do isolamento térmico', 'TEXT', NULL, TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Medição do diferencial', 'TEXT', NULL, TRUE, TRUE, 11);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (47, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB, TRUE, TRUE, 12);

-- PMOC > PMOC MENSAL Cortina de ar
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (48, 'Tag do equipamento', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (48, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (48, 'Verificação e limpeza da carenagem', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (48, 'Verificação e limpeza da turbina', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (48, 'Verificação e limpeza dos defletores', 'TEXT', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (48, 'Verificação e limpeza do direcionamento de ar', 'TEXT', NULL, TRUE, TRUE, 6);

-- PMOC > PMOC SEMESTRAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Tag do equipamento', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificar a operação de drenagem de água da bandeja e realizar limpeza do dreno', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Lavar o gabinete, as bandejas e as serpentinas, sem o uso de produtos desengraxantes e corrosivos', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Limpar os ventiladores (carcaça e rotor)', 'TEXT', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Filtro verificar e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas; ', 'TEXT', NULL, TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificar presença de ruídos e/ou vibrações anormais', 'TEXT', NULL, TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificar a vedação dos painéis de fechamento do gabinete', 'TEXT', NULL, TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL, TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificar o estado de conservação do isolamento térmico', 'TEXT', NULL, TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificação de existência de vazamentos', 'TEXT', NULL, TRUE, TRUE, 11);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Técnico responsável', 'SINGLE_SELECT', '["Rodrigo Silveira", "Bruno Silveira"]'::JSONB, TRUE, TRUE, 12);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Leituras de tensão', 'TEXT', NULL, TRUE, TRUE, 13);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Leitura de corrente', 'TEXT', NULL, TRUE, TRUE, 14);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Leitura de pressão', 'TEXT', NULL, TRUE, TRUE, 15);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificação de terminais', 'TEXT', NULL, TRUE, TRUE, 16);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Verificação de fiação e contatos', 'TEXT', NULL, TRUE, TRUE, 17);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Reaperto de conexões', 'TEXT', NULL, TRUE, TRUE, 18);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (49, 'Medição de diferencial', 'TEXT', NULL, TRUE, TRUE, 19);

-- PMOC > PMOC SEMESTRAL Cortina de ar
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Tag do equipamento', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Limpeza dos componentes elétricos', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Verificar conexões eletricas', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Lubrificação do eixo e do sistema de fixação da turbina', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Limpeza de carenagem', 'TEXT', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Limpeza de turbina', 'TEXT', NULL, TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Limpeza do direcionamento de ar', 'TEXT', NULL, TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Medição de corrente', 'TEXT', NULL, TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (50, 'Medição de tensão', 'TEXT', NULL, TRUE, TRUE, 9);

-- PMOC > PMOC TRIMESTRAL
INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Tag do equipamento', 'TEXT', NULL, TRUE, TRUE, 1);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Verificar e eliminar danos e/ou corrosão no gabinete, na bandeja e nas serpentinas', 'TEXT', NULL, TRUE, TRUE, 2);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Verificar a operação de drenagem de água da bandeja e realizar limpeza do dreno', 'TEXT', NULL, TRUE, TRUE, 3);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Lavar o gabinete, as bandejas e as serpentinas, sem o uso de produtos desengraxantes e corrosivos', 'TEXT', NULL, TRUE, TRUE, 4);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Limpar os ventiladores (carcaça e rotor)', 'TEXT', NULL, TRUE, TRUE, 5);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Filtro verificar e eliminar sujeira, danos e presença de corrosão, verificar e eliminar as frestas; ', 'TEXT', NULL, TRUE, TRUE, 6);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Verificar presença de ruídos e/ou vibrações anormais', 'TEXT', NULL, TRUE, TRUE, 7);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Verificar a vedação dos painéis de fechamento do gabinete', 'TEXT', NULL, TRUE, TRUE, 8);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Verificação de temperaturas c° de insuflamento, ambiente interno.ref (8 - 14c°)', 'TEXT', NULL, TRUE, TRUE, 9);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Verificar o estado de conservação do isolamento térmico', 'TEXT', NULL, TRUE, TRUE, 10);

INSERT INTO SERVICE_FIELD_TYPE
    (ID_SERVICE_TYPE, NAME, TYPE, OPTIONS, REQUIRED, ACTIVE, DISPLAY_ORDER)
VALUES (51, 'Medição de diferencial', 'TEXT', NULL, TRUE, TRUE, 11);

COMMIT;
