-- Arquivo gerado automaticamente a partir da planilha de chamados
-- Categorias: 11
-- Tipos de chamado: 51
-- Tipos de campos: 527
-- Valores de campos: 6663

-- =========================
-- SERVICE_CATEGORY
-- =========================
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (1, 'ARTÍFICE');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (2, 'PINTURA DE SINALIZAÇÃO DE SEGURANÇA/OPERACIONAL/PREDIAL/METÁLICA');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (3, 'COPA');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (4, 'Dúvida Aplicativo');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (5, 'NOVOS PROJETOS');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (6, 'INSTALAÇÕES HIDRÁULICAS');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (7, 'INSTALAÇÕES ELÉTRICAS');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (8, 'CLIMATIZAÇÃO E REFRIGERAÇÃO');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (9, 'MANUTENÇÂO CIVIL');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (10, 'PMOC');
INSERT INTO SERVICE_CATEGORY (ID, NAME) VALUES (11, 'JARDINAGEM');
