-- Falha antes de inserir se qualquer tabela de destino estiver povoada.
DECLARE
    n NUMBER;
BEGIN
    EXECUTE IMMEDIATE 'LOCK TABLE OHFC_IMPORT_TICKET IN EXCLUSIVE MODE NOWAIT';
    SELECT COUNT(*) INTO n FROM OHFC_IMPORT_TICKET;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20001, 'OHFC_IMPORT_TICKET deve estar vazia'); END IF;
    EXECUTE IMMEDIATE 'LOCK TABLE OHFC_IMPORT_SNAPSHOT IN EXCLUSIVE MODE NOWAIT';
    SELECT COUNT(*) INTO n FROM OHFC_IMPORT_SNAPSHOT;
    IF n <> 0 THEN RAISE_APPLICATION_ERROR(-20001, 'OHFC_IMPORT_SNAPSHOT deve estar vazia'); END IF;
END;
/
