-- Confere totais e avança identities sem DDL nem commit intermediário.
DECLARE
    n NUMBER;
    seq_name VARCHAR2(128);
    increment_value NUMBER;
    next_id NUMBER;
BEGIN
    SELECT COUNT(*) INTO n FROM OHFC_IMPORT_TICKET;
    IF n <> 1675 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_IMPORT_TICKET'); END IF;
    SELECT COUNT(*) INTO n FROM OHFC_IMPORT_SNAPSHOT;
    IF n <> 1675 THEN RAISE_APPLICATION_ERROR(-20002, 'Total divergente: OHFC_IMPORT_SNAPSHOT'); END IF;
    SELECT I.SEQUENCE_NAME, S.INCREMENT_BY INTO seq_name, increment_value
    FROM USER_TAB_IDENTITY_COLS I JOIN USER_SEQUENCES S ON S.SEQUENCE_NAME=I.SEQUENCE_NAME
    WHERE I.TABLE_NAME='OHFC_IMPORT_SNAPSHOT' AND I.COLUMN_NAME='ID';
    IF increment_value <= 0 THEN RAISE_APPLICATION_ERROR(-20003, 'Identity deve ser crescente'); END IF;
    LOOP
        EXECUTE IMMEDIATE 'SELECT ' || DBMS_ASSERT.ENQUOTE_NAME(seq_name, FALSE) || '.NEXTVAL FROM DUAL' INTO next_id;
        EXIT WHEN next_id > 1675;
    END LOOP;
END;
/
COMMIT;
