SELECT RST.ID AS Numero,
	   RTP.NAME AS Tipo_de_solicitacao,
	   RSS.DESCRIPTION AS Status,
	   SVC.NAME AS Categoria,
	   SVT.NAME AS Servico,
	   BNS.NAME AS Unidade_de_negocio,
	   RGN.NAME AS Regiao,
	   LOC.NAME AS Localizacao,
	   RST.CREATED_DATE AS Data_de_solicitacao,
	   RST.STARTED_DATE AS Data_de_inicio,
	   RST.FINISHED_DATE AS Data_de_encerramento,
	   RST.DESCRIPTION AS Descricao
	FROM REQUEST AS RST
		INNER JOIN REQUEST_TYPE AS RTP
		 	ON RST.ID_REQUEST_TYPE = RTP.ID
		INNER JOIN REQUEST_STATUS AS RSS
		 	ON RST.ID_REQUEST_STATUS = RSS.ID
		INNER JOIN LOCATION AS LOC
			ON RST.ID_LOCATION = LOC.ID
	    INNER JOIN REGION AS RGN
			ON LOC.ID_REGION = RGN.ID 
		INNER JOIN BUSINESS AS BNS
			ON RGN.ID_BUSINESS = BNS.ID
		INNER JOIN SERVICE_TYPE AS SVT
			ON RST.ID_SERVICE_TYPE = SVT.ID
		INNER JOIN SERVICE_CATEGORY AS SVC
			ON SVT.ID_SERVICE_CATEGORY = SVC.ID
		WHERE RST.ID_REQUEST_STATUS IN (2,3,4)
			ORDER BY RST.ID;