-- OHFC_SERVICE_CATEGORY: 11 registros. Gerado pelas regras revisadas da importação.
-- Sem COMMIT individual; executar pelo consolidado ou RUN_SQLPLUS.sql.

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    1,
    'ARTÍFICE'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    2,
    'CLIMATIZAÇÃO E REFRIGERAÇÃO'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    3,
    'COPA'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    4,
    'INSTALAÇÕES ELÉTRICAS'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    5,
    'INSTALAÇÕES HIDRÁULICAS'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    6,
    'JARDINAGEM'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    7,
    'MANUTENÇÂO CIVIL'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    8,
    'NOVOS PROJETOS'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    9,
    'PINTURA'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    10,
    'PMOC'
);

INSERT INTO OHFC_SERVICE_CATEGORY (ID, NAME)
VALUES (
    11,
    'Dúvida Aplicativo'
);
