-- ============================================================
-- OpsHub - Carga inicial completa de CHECKLIST_TYPE
-- Origem: 34 arquivos XLSX (20 do primeiro lote + 14 do segundo lote).
-- ============================================================

BEGIN;

INSERT INTO CHECKLIST_TYPE
(
    NAME,
    DESCRIPTION,
    VERSION,
    ACTIVE
)
VALUES
    ('BOMBA LAMEIRA/VÁCUO', NULL, '01/2018', TRUE),
    ('CJ BARCO E MOTOR', NULL, '01/2018', TRUE),
    ('COMPACTADOR A PERCUSSÃO', NULL, '01/2018', TRUE),
    ('ESMERIL', NULL, '01/2018', TRUE),
    ('ESMERILHADEIRA / LIXADEIRA OU POLICORTE', NULL, '01/2018', TRUE),
    ('FURADEIRA SDS e MANDRIL / PARAFUSADEIRA / MARTELO PERFURADOR', NULL, '01/2018', TRUE),
    ('GERADOR', NULL, '00/2018', TRUE),
    ('GRAB', NULL, '01/2018', TRUE),
    ('CONJUNTO OXI-ACETILENO', NULL, '01/2018', TRUE),
    ('MAÇARICO GLP', NULL, '01/2018', TRUE),
    ('MÁQUINA DE PINTURA AIRLESS', NULL, '01/2018', TRUE),
    ('PERFURATRIZ', NULL, '01/2018', TRUE),
    ('PLACA VIBRATÓRIA', NULL, '01/2018', TRUE),
    ('SERRA TICO TICO', NULL, '01/2018', TRUE),
    ('ANDAIME', NULL, '06/2019', TRUE),
    ('BETONEIRA', NULL, '01/2018', TRUE),
    ('CINTO DE SEGURANÇA E TALABARTE', NULL, '01/2018', TRUE),
    ('COMPRESSOR DE AR', NULL, '01/2018', TRUE),
    ('ENCERADEIRA', NULL, '01/2018', TRUE),
    ('ESCADA PORTÁTIL', NULL, '01/2018', TRUE);
    ('FURADEIRA DE BANCADA', NULL, '01/2018', TRUE),
    ('LAVADORA DE ALTA PRESSÃO A GASOLINA', NULL, '01/2018', TRUE),
    ('LAVADORA DE ALTA PRESSÃO ELÉTRICO', NULL, '01/2018', TRUE),
    ('MÁQUINA DE SOLDA', NULL, '01/2018', TRUE),
    ('MARTELETE PNEUMÁTICO/ELETRICO', NULL, '01/2018', TRUE),
    ('MINICARREGADEIRA', NULL, '01/2018', TRUE),
    ('MOTOSSERRA', NULL, '01/2018', TRUE),
    ('PLATAFORMA DE TRABALHO AEREA', NULL, '01/2018', TRUE),
    ('RETIFICADORA', NULL, '01/2018', TRUE),
    ('RETROESCAVADEIRA E ESCAVADEIRA', NULL, '06/2019', TRUE),
    ('ROÇADEIRA', NULL, '01/2018', TRUE),
    ('ROLO COMPACTADOR', NULL, '01/2018', TRUE),
    ('SERRA MÁRMORE', NULL, '01/2018', TRUE),
    ('SOPRADOR TÉRMICO', NULL, '01/2018', TRUE);

COMMIT;
