"""Explicit physical columns; aliases are unpacked by the connection row mapper."""
COLUMNS = {'OHFC_BUSINESS': ['ID', 'NAME'],
 'OHFC_CHECKLIST_FIELD_TYPE': ['ID',
                               'ID_CHECKLIST_TYPE',
                               'NAME',
                               'TYPE',
                               'OPTIONS',
                               'REQUIRED',
                               'ACTIVE',
                               'DISPLAY_ORDER'],
 'OHFC_CHECKLIST_FIELD_VALUE': ['ID',
                                'ID_CHECKLIST_FIELD_TYPE',
                                'ID_REQUEST_TASK_CHECKLIST',
                                'VALUE'],
 'OHFC_CHECKLIST_TYPE': ['ID', 'NAME', 'DESCRIPTION', 'VERSION', 'ACTIVE'],
 'OHFC_LOCATION': ['ID', 'ID_REGION', 'NAME', 'LOCATION_X', 'LOCATION_Y'],
 'OHFC_MEMBERSHIP': ['ID', 'ID_SECTOR', 'NAME', 'EMAIL', 'ACCESS_LEVEL'],
 'OHFC_REGION': ['ID', 'ID_BUSINESS', 'NAME'],
 'OHFC_REQUEST': ['ID',
                  'ID_REQUEST_TYPE',
                  'ID_MEMBERSHIP_REQUESTER',
                  'ID_MEMBERSHIP_RESPONDER',
                  'ID_LOCATION',
                  'ID_SERVICE_TYPE',
                  'ID_REQUEST_STATUS',
                  'CREATED_DATE',
                  'AGREED_DATE',
                  'STARTED_DATE',
                  'FINISHED_DATE',
                  'CANCELED_DATE',
                  'DESCRIPTION'],
 'OHFC_REQUEST_STATUS': ['ID', 'DESCRIPTION'],
 'OHFC_REQUEST_TASK': ['ID', 'ID_REQUEST', 'STARTED_DATE', 'FINISHED_DATE', 'DESCRIPTION'],
 'OHFC_REQUEST_TASK_CHECKLIST': ['ID',
                                 'ID_CHECKLIST_TYPE',
                                 'ID_REQUEST_TASK',
                                 'CORPORATION',
                                 'EQUIPMENT_TAG',
                                 'EQUIPMENT_BRAND',
                                 'EQUIPMENT_MODEL',
                                 'RENTED_EQUIPMENT',
                                 'SERIAL_NUMBER',
                                 'PT_NUMBER'],
 'OHFC_REQUEST_TASK_MEDIA': ['ID',
                             'ID_REQUEST_TASK',
                             'CONTENT',
                             'FILE_NAME',
                             'MIME_TYPE',
                             'FILE_SIZE',
                             'CREATED_DATE'],
 'OHFC_REQUEST_TRANSACTION': ['ID',
                              'ID_REQUEST',
                              'ID_MEMBERSHIP_REQUESTER',
                              'ID_MEMBERSHIP_RESPONDER',
                              'ID_REQUEST_TRANSACTION_STATUS',
                              'DESCRIPTION'],
 'OHFC_REQUEST_TRANSACTION_STATUS': ['ID', 'DESCRIPTION'],
 'OHFC_REQUEST_TYPE': ['ID', 'NAME'],
 'OHFC_SECTOR': ['ID', 'NAME', 'ACCESS_LEVELS'],
 'OHFC_SERVICE_CATEGORY': ['ID', 'NAME'],
 'OHFC_SERVICE_FIELD_MEDIA': ['ID',
                              'ID_SERVICE_FIELD_TYPE',
                              'ID_REQUEST',
                              'CONTENT',
                              'FILE_NAME',
                              'MIME_TYPE',
                              'FILE_SIZE',
                              'CREATED_DATE'],
 'OHFC_SERVICE_FIELD_TYPE': ['ID',
                             'ID_SERVICE_TYPE',
                             'NAME',
                             'TYPE',
                             'OPTIONS',
                             'REQUIRED',
                             'ACTIVE',
                             'DISPLAY_ORDER'],
 'OHFC_SERVICE_FIELD_VALUE': ['ID', 'ID_SERVICE_FIELD_TYPE', 'ID_REQUEST', 'VALUE'],
 'OHFC_SERVICE_TYPE': ['ID', 'ID_SERVICE_CATEGORY', 'NAME', 'DESCRIPTION'],
 'OHFC_SLA': ['ID', 'NAME', 'DESCRIPTION', 'DEADLINE'],
 'OHFC_TASK_MEMBER_OCCURRENCE': ['ID', 'ID_REQUEST_TASK', 'ID_MEMBERSHIP']}


def projection(table: str, alias: str, group: str) -> str:
    # All arguments originate in source code, never in request input.
    return ", ".join(f'{alias}.{column} AS "{group}__{column.lower()}"' for column in COLUMNS[table])
