CREATE TABLE request (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_request_type INTEGER NOT NULL,
    id_member_requester INTEGER NOT NULL,
    id_member_responder INTEGER,
    id_location INTEGER,
    id_service_type INTEGER NOT NULL,
    id_request_status INTEGER NOT NULL,
    Created_date TIMESTAMP,
    Agreed_date TIMESTAMP,
    Started_date TIMESTAMP,
    Finished_date TIMESTAMP,
    Canceled_date TIMESTAMP,
    description VARCHAR(300),

    CONSTRAINT fk_request_request_type
        FOREIGN KEY (id_request_type)
        REFERENCES request_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_request_member_requester
        FOREIGN KEY (id_member_requester)
        REFERENCES membership (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_request_member_responder
        FOREIGN KEY (id_member_responder)
        REFERENCES membership (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_request_location
        FOREIGN KEY (id_location)
        REFERENCES location (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_request_service_type
        FOREIGN KEY (id_service_type)
        REFERENCES service_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,


    CONSTRAINT fk_request_status
    FOREIGN KEY (id_request_status)
    REFERENCES REQUEST_STATUS (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT

);