INSERT INTO MEMBERSHIP (NAME, EMAIL)
VALUES
    (E'Ademilson Alves Dos Santos', E'ademilson.santos@wilsonsons.com.br'),
    (E'Alan Cunha', E'alan.cunha@wilsonsons.com.br'),
    (E'Alexandro Vieira Dos Santos', E'alexandro.santos@wilsonsons.com.br'),
    (E'Aloisio Junior', E'aloisio.junior@wilsonsons.com.br'),
    (E'Aldericio Lima Souza Junior', E'alsj@wilsonsons.com.br'),
    (E'Ana Paula', E'anapaula.antonio@wilsonsons.com.br'),
    (E'Anisio Filho', E'anisio.filho@wilsonsons.com.br'),
    (E'Antônio Baqueiro Costa', E'antonio.baqueiro@wilsonsons.com.br'),
    (E'Antonio Felipe Da Silva', E'antonio.silva@wilsonsons.com.br'),
    (E'Antonio', E'antoniobaqueirocosta@gmail.com'),
    (E'Luis Henrique Dos Santos Borba', E'borb@wilsonsons.com.br'),
    (E'Braian Costa', E'braian.costa@wilsonsons.com.br'),
    (E'Bruno Caldas', E'bruno.caldas@wilsonsons.com.br'),
    (E'Caio Breno Cerqueira Andrade', E'caio.andrade@wilsonsons.com.br'),
    (E'Clara Santos', E'clara.santos@wilsonsons.com.br'),
    (E'Daniel Conceição Dos Santos Filho', E'dcdf@wilsonsons.com.br'),
    (E'Debora Silveira', E'debora.silveira@wilsonsons.com.br'),
    (E'Desiree Nunes', E'desiree.nunes@wilsonsons.com.br'),
    (E'Emerson Melo', E'emerson.melo@wilsonsons.com.br'),
    (E'Evelyn Barbosa', E'evelyn.barbosa@wilsonsons.com.br'),
    (E'Fabio Nazareno', E'fabio.nazareno@wilsonsons.com.br'),
    (E'Felipe Da Costa Purificacao', E'fdcp@wilsonsons.com.br'),
    (E'Felipe Purificação', E'felipe.purificacao@wilsonsons.com.br'),
    (E'Gabriela Brito', E'gabriela.brito@wilsonsons.com.br'),
    (E'Gabrielle Paz', E'gabrielle.silva@wilsonsons.com.br'),
    (E'Gilson Souza', E'gilson.souza@wilsonsons.com.br'),
    (E'Guilherme Miranda', E'guilherme.miranda@wilsonsons.com.br'),
    (E'Igor Freitas', E'igor.freitas@wilsonsons.com.br'),
    (E'Isabella Valverde Santos', E'isabella.santos@wilsonsons.com.br'),
    (E'Isys Hanaira Mato Grosso Souza', E'isys.grosso@wilsonsons.com.br'),
    (E'Jean Bastos', E'jean.bastos@wilsonsons.com.br'),
    (E'Jennifer Andrade', E'jennifer.andrade@wilsonsons.com.br'),
    (E'João Lima', E'joao.lima@wilsonsons.com.br'),
    (E'Joel Roseno', E'joel.roseno@wilsonsons.com.br'),
    (E'Joice Santana', E'joice.santana@wilsonsons.com.br'),
    (E'Josafa Silva Dos Santos', E'josafa.santos@wilsonsons.com.br'),
    (E'José Carlos', E'josecarlos.silva@wilsonsons.com.br'),
    (E'Juliana Caldas', E'juliana.caldas@wilsonsons.com.br'),
    (E'Laise Almeida', E'laise.almeida@wilsonsons.com.br'),
    (E'Laiza Menezes', E'laiza.menezes@wilsonsons.com.br'),
    (E'Lara Sena', E'lara.sena@wilsonsons.com.br'),
    (E'Larissa Martins', E'larissa.martins@wilsonsons.com.br'),
    (E'Lilia Figueredo', E'lilia.figueredo@wilsonsons.com.br'),
    (E'Lorena Paiva', E'lorena.paiva@wilsonsons.com.br'),
    (E'Luis Cerqueira', E'luis.cerqueira@wilsonsons.com.br'),
    (E'Malu Caldas', E'malu.caldas@wilsonsons.com.br'),
    (E'Marcela Macedo', E'marcela.macedo@wilsonsons.com.br'),
    (E'Marcelo Santos', E'marcelo.santos@wilsonsons.com.br'),
    (E'Marilia Silva', E'marilia.silva@wilsonsons.com.br'),
    (E'Matheus Costa', E'matheus.costa@wilsonsons.com.br'),
    (E'Teste Deskbee', E'matheus.medeiros@deskbee.co'),
    (E'Marcelo Lima De Jesus', E'mldj@wilsonsons.com.br'),
    (E'Marcos Santos De Almeida', E'msad@wilsonsons.com.br'),
    (E'Rodrigo Silveira Dos Santos', E'nexz@wilsonsons.com.br'),
    (E'Patricia Andrade', E'patricia.andrade@wilsonsons.com.br'),
    (E'Phs2026Novo22@', E'pedro.bispo@wilsonsons.com.br'),
    (E'Pedro Melo', E'pedro.melo@wilsonsons.com.br'),
    (E'Rodrigo Gomes', E'rodrigo.gomes@wilsonsons.com.br'),
    (E'Rodrigo Silveira Dos Santos', E'rodrigosilveira05310@gmail.com'),
    (E'Rogerio Santos Garcia', E'rsag@wilsonsons.com.br'),
    (E'Sally Crisley', E'sally.silva@wilsonsons.com.br'),
    (E'Sara Pereira', E'sara.pereira@wilsonsons.com.br'),
    (E'Sarah Nascimento', E'sarah.nascimento@wilsonsons.com.br'),
    (E'Lucas Oliveira Rocha', E't_luro@wilsonsons.com.br'),
    (E'Thiago Andrade Claudiano Dos Santos', E'tacd@wilsonsons.com.br'),
    (E'Taila Oliveira', E'taila.oliveira@wilsonsons.com.br'),
    (E'Tainara Carmo', E'tainara.carmo@wilsonsons.com.br'),
    (E'Thais Brito', E'thais.brito@wilsonsons.com.br'),
    (E'Thayse Passos', E'thayse.passos@wilsonsons.com.br'),
    (E'Thiago Andrade Claudiano Dos Santos', E'thiagotecnic@outlook.com'),
    (E'Valeria Santos', E'valeria.santos@wilsonsons.com.br'),
    (E'Vanessa Lima', E'vanessa.lima@wilsonsons.com.br'),
    (E'Vitor Jesus', E'vitor.jesus@wilsonsons.com.br'),
    (E'Vitoria Gois', E'vitoria.gois@wilsonsons.com.br');