INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("TI", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Almoxarifado", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Armazém", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Atendimento", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Comercial", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Engenharia", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Faturamento", 3);   
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Facilities", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Manutenção", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Operações", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("QSMSP", 3);
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("RH", 3);


