INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("TI");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Almoxarifado");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Armazém");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Atendimento");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Comercial");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Engenharia");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Faturamento");   
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Facilities");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Manutenção");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("Operações");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("QSMSP");
INSERT INTO SECTOR ( NAME, ACCESS_LEVELS) VALUES ("RH");


